// Code generated by "enumer -type=ChunkKind,ScopeKind,Visibility,ChunkState,EntryKind,EntryState,LinkKind,LinkState,RiskClass,VerificationStatus,EvidenceType,EvidenceQuality,PersonalOrigin,ObjectKind,ActorKind -trimprefix=ChunkKind,ScopeKind,Visibility,ChunkState,EntryKind,EntryState,LinkKind,LinkState,RiskClass,VerificationStatus,EvidenceType,EvidenceQuality,PersonalOrigin,ObjectKind,ActorKind -transform=snake -json -text -values -output=enums_enumer.go"; DO NOT EDIT.

package knowledge

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ChunkKindName = "unspecifiedreferencepersonalprojectenvironment"

var _ChunkKindIndex = [...]uint8{0, 11, 20, 28, 35, 46}

const _ChunkKindLowerName = "unspecifiedreferencepersonalprojectenvironment"

func (i ChunkKind) String() string {
	if i >= ChunkKind(len(_ChunkKindIndex)-1) {
		return fmt.Sprintf("ChunkKind(%d)", i)
	}
	return _ChunkKindName[_ChunkKindIndex[i]:_ChunkKindIndex[i+1]]
}

func (ChunkKind) Values() []string {
	return ChunkKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ChunkKindNoOp() {
	var x [1]struct{}
	_ = x[ChunkKindUnspecified-(0)]
	_ = x[ChunkKindReference-(1)]
	_ = x[ChunkKindPersonal-(2)]
	_ = x[ChunkKindProject-(3)]
	_ = x[ChunkKindEnvironment-(4)]
}

var _ChunkKindValues = []ChunkKind{ChunkKindUnspecified, ChunkKindReference, ChunkKindPersonal, ChunkKindProject, ChunkKindEnvironment}

var _ChunkKindNameToValueMap = map[string]ChunkKind{
	_ChunkKindName[0:11]:       ChunkKindUnspecified,
	_ChunkKindLowerName[0:11]:  ChunkKindUnspecified,
	_ChunkKindName[11:20]:      ChunkKindReference,
	_ChunkKindLowerName[11:20]: ChunkKindReference,
	_ChunkKindName[20:28]:      ChunkKindPersonal,
	_ChunkKindLowerName[20:28]: ChunkKindPersonal,
	_ChunkKindName[28:35]:      ChunkKindProject,
	_ChunkKindLowerName[28:35]: ChunkKindProject,
	_ChunkKindName[35:46]:      ChunkKindEnvironment,
	_ChunkKindLowerName[35:46]: ChunkKindEnvironment,
}

var _ChunkKindNames = []string{
	_ChunkKindName[0:11],
	_ChunkKindName[11:20],
	_ChunkKindName[20:28],
	_ChunkKindName[28:35],
	_ChunkKindName[35:46],
}

// ChunkKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ChunkKindString(s string) (ChunkKind, error) {
	if val, ok := _ChunkKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ChunkKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ChunkKind values", s)
}

// ChunkKindValues returns all values of the enum
func ChunkKindValues() []ChunkKind {
	return _ChunkKindValues
}

// ChunkKindStrings returns a slice of all String values of the enum
func ChunkKindStrings() []string {
	strs := make([]string, len(_ChunkKindNames))
	copy(strs, _ChunkKindNames)
	return strs
}

// IsAChunkKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ChunkKind) IsAChunkKind() bool {
	for _, v := range _ChunkKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ChunkKind
func (i ChunkKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ChunkKind
func (i *ChunkKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ChunkKind should be a string, got %s", data)
	}

	var err error
	*i, err = ChunkKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ChunkKind
func (i ChunkKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ChunkKind
func (i *ChunkKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = ChunkKindString(string(text))
	return err
}

const _ScopeKindName = "unspecifiedglobalpersonalprojectsessionenvironment"

var _ScopeKindIndex = [...]uint8{0, 11, 17, 25, 32, 39, 50}

const _ScopeKindLowerName = "unspecifiedglobalpersonalprojectsessionenvironment"

func (i ScopeKind) String() string {
	if i >= ScopeKind(len(_ScopeKindIndex)-1) {
		return fmt.Sprintf("ScopeKind(%d)", i)
	}
	return _ScopeKindName[_ScopeKindIndex[i]:_ScopeKindIndex[i+1]]
}

func (ScopeKind) Values() []string {
	return ScopeKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ScopeKindNoOp() {
	var x [1]struct{}
	_ = x[ScopeKindUnspecified-(0)]
	_ = x[ScopeKindGlobal-(1)]
	_ = x[ScopeKindPersonal-(2)]
	_ = x[ScopeKindProject-(3)]
	_ = x[ScopeKindSession-(4)]
	_ = x[ScopeKindEnvironment-(5)]
}

var _ScopeKindValues = []ScopeKind{ScopeKindUnspecified, ScopeKindGlobal, ScopeKindPersonal, ScopeKindProject, ScopeKindSession, ScopeKindEnvironment}

var _ScopeKindNameToValueMap = map[string]ScopeKind{
	_ScopeKindName[0:11]:       ScopeKindUnspecified,
	_ScopeKindLowerName[0:11]:  ScopeKindUnspecified,
	_ScopeKindName[11:17]:      ScopeKindGlobal,
	_ScopeKindLowerName[11:17]: ScopeKindGlobal,
	_ScopeKindName[17:25]:      ScopeKindPersonal,
	_ScopeKindLowerName[17:25]: ScopeKindPersonal,
	_ScopeKindName[25:32]:      ScopeKindProject,
	_ScopeKindLowerName[25:32]: ScopeKindProject,
	_ScopeKindName[32:39]:      ScopeKindSession,
	_ScopeKindLowerName[32:39]: ScopeKindSession,
	_ScopeKindName[39:50]:      ScopeKindEnvironment,
	_ScopeKindLowerName[39:50]: ScopeKindEnvironment,
}

var _ScopeKindNames = []string{
	_ScopeKindName[0:11],
	_ScopeKindName[11:17],
	_ScopeKindName[17:25],
	_ScopeKindName[25:32],
	_ScopeKindName[32:39],
	_ScopeKindName[39:50],
}

// ScopeKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ScopeKindString(s string) (ScopeKind, error) {
	if val, ok := _ScopeKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ScopeKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ScopeKind values", s)
}

// ScopeKindValues returns all values of the enum
func ScopeKindValues() []ScopeKind {
	return _ScopeKindValues
}

// ScopeKindStrings returns a slice of all String values of the enum
func ScopeKindStrings() []string {
	strs := make([]string, len(_ScopeKindNames))
	copy(strs, _ScopeKindNames)
	return strs
}

// IsAScopeKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ScopeKind) IsAScopeKind() bool {
	for _, v := range _ScopeKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ScopeKind
func (i ScopeKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ScopeKind
func (i *ScopeKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ScopeKind should be a string, got %s", data)
	}

	var err error
	*i, err = ScopeKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ScopeKind
func (i ScopeKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ScopeKind
func (i *ScopeKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = ScopeKindString(string(text))
	return err
}

const _VisibilityName = "unspecifiedprivateinstallationsharedpublic"

var _VisibilityIndex = [...]uint8{0, 11, 18, 30, 36, 42}

const _VisibilityLowerName = "unspecifiedprivateinstallationsharedpublic"

func (i Visibility) String() string {
	if i >= Visibility(len(_VisibilityIndex)-1) {
		return fmt.Sprintf("Visibility(%d)", i)
	}
	return _VisibilityName[_VisibilityIndex[i]:_VisibilityIndex[i+1]]
}

func (Visibility) Values() []string {
	return VisibilityStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _VisibilityNoOp() {
	var x [1]struct{}
	_ = x[VisibilityUnspecified-(0)]
	_ = x[VisibilityPrivate-(1)]
	_ = x[VisibilityInstallation-(2)]
	_ = x[VisibilityShared-(3)]
	_ = x[VisibilityPublic-(4)]
}

var _VisibilityValues = []Visibility{VisibilityUnspecified, VisibilityPrivate, VisibilityInstallation, VisibilityShared, VisibilityPublic}

var _VisibilityNameToValueMap = map[string]Visibility{
	_VisibilityName[0:11]:       VisibilityUnspecified,
	_VisibilityLowerName[0:11]:  VisibilityUnspecified,
	_VisibilityName[11:18]:      VisibilityPrivate,
	_VisibilityLowerName[11:18]: VisibilityPrivate,
	_VisibilityName[18:30]:      VisibilityInstallation,
	_VisibilityLowerName[18:30]: VisibilityInstallation,
	_VisibilityName[30:36]:      VisibilityShared,
	_VisibilityLowerName[30:36]: VisibilityShared,
	_VisibilityName[36:42]:      VisibilityPublic,
	_VisibilityLowerName[36:42]: VisibilityPublic,
}

var _VisibilityNames = []string{
	_VisibilityName[0:11],
	_VisibilityName[11:18],
	_VisibilityName[18:30],
	_VisibilityName[30:36],
	_VisibilityName[36:42],
}

// VisibilityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func VisibilityString(s string) (Visibility, error) {
	if val, ok := _VisibilityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _VisibilityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Visibility values", s)
}

// VisibilityValues returns all values of the enum
func VisibilityValues() []Visibility {
	return _VisibilityValues
}

// VisibilityStrings returns a slice of all String values of the enum
func VisibilityStrings() []string {
	strs := make([]string, len(_VisibilityNames))
	copy(strs, _VisibilityNames)
	return strs
}

// IsAVisibility returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Visibility) IsAVisibility() bool {
	for _, v := range _VisibilityValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Visibility
func (i Visibility) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Visibility
func (i *Visibility) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Visibility should be a string, got %s", data)
	}

	var err error
	*i, err = VisibilityString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Visibility
func (i Visibility) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Visibility
func (i *Visibility) UnmarshalText(text []byte) error {
	var err error
	*i, err = VisibilityString(string(text))
	return err
}

const _ChunkStateName = "unspecifieddraftactivearchived"

var _ChunkStateIndex = [...]uint8{0, 11, 16, 22, 30}

const _ChunkStateLowerName = "unspecifieddraftactivearchived"

func (i ChunkState) String() string {
	if i >= ChunkState(len(_ChunkStateIndex)-1) {
		return fmt.Sprintf("ChunkState(%d)", i)
	}
	return _ChunkStateName[_ChunkStateIndex[i]:_ChunkStateIndex[i+1]]
}

func (ChunkState) Values() []string {
	return ChunkStateStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ChunkStateNoOp() {
	var x [1]struct{}
	_ = x[ChunkStateUnspecified-(0)]
	_ = x[ChunkStateDraft-(1)]
	_ = x[ChunkStateActive-(2)]
	_ = x[ChunkStateArchived-(3)]
}

var _ChunkStateValues = []ChunkState{ChunkStateUnspecified, ChunkStateDraft, ChunkStateActive, ChunkStateArchived}

var _ChunkStateNameToValueMap = map[string]ChunkState{
	_ChunkStateName[0:11]:       ChunkStateUnspecified,
	_ChunkStateLowerName[0:11]:  ChunkStateUnspecified,
	_ChunkStateName[11:16]:      ChunkStateDraft,
	_ChunkStateLowerName[11:16]: ChunkStateDraft,
	_ChunkStateName[16:22]:      ChunkStateActive,
	_ChunkStateLowerName[16:22]: ChunkStateActive,
	_ChunkStateName[22:30]:      ChunkStateArchived,
	_ChunkStateLowerName[22:30]: ChunkStateArchived,
}

var _ChunkStateNames = []string{
	_ChunkStateName[0:11],
	_ChunkStateName[11:16],
	_ChunkStateName[16:22],
	_ChunkStateName[22:30],
}

// ChunkStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ChunkStateString(s string) (ChunkState, error) {
	if val, ok := _ChunkStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ChunkStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ChunkState values", s)
}

// ChunkStateValues returns all values of the enum
func ChunkStateValues() []ChunkState {
	return _ChunkStateValues
}

// ChunkStateStrings returns a slice of all String values of the enum
func ChunkStateStrings() []string {
	strs := make([]string, len(_ChunkStateNames))
	copy(strs, _ChunkStateNames)
	return strs
}

// IsAChunkState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ChunkState) IsAChunkState() bool {
	for _, v := range _ChunkStateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ChunkState
func (i ChunkState) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ChunkState
func (i *ChunkState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ChunkState should be a string, got %s", data)
	}

	var err error
	*i, err = ChunkStateString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ChunkState
func (i ChunkState) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ChunkState
func (i *ChunkState) UnmarshalText(text []byte) error {
	var err error
	*i, err = ChunkStateString(string(text))
	return err
}

const _EntryKindName = "unspecifiedfactprocedureconceptwarningpreferencedecisionreference"

var _EntryKindIndex = [...]uint8{0, 11, 15, 24, 31, 38, 48, 56, 65}

const _EntryKindLowerName = "unspecifiedfactprocedureconceptwarningpreferencedecisionreference"

func (i EntryKind) String() string {
	if i >= EntryKind(len(_EntryKindIndex)-1) {
		return fmt.Sprintf("EntryKind(%d)", i)
	}
	return _EntryKindName[_EntryKindIndex[i]:_EntryKindIndex[i+1]]
}

func (EntryKind) Values() []string {
	return EntryKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EntryKindNoOp() {
	var x [1]struct{}
	_ = x[EntryKindUnspecified-(0)]
	_ = x[EntryKindFact-(1)]
	_ = x[EntryKindProcedure-(2)]
	_ = x[EntryKindConcept-(3)]
	_ = x[EntryKindWarning-(4)]
	_ = x[EntryKindPreference-(5)]
	_ = x[EntryKindDecision-(6)]
	_ = x[EntryKindReference-(7)]
}

var _EntryKindValues = []EntryKind{EntryKindUnspecified, EntryKindFact, EntryKindProcedure, EntryKindConcept, EntryKindWarning, EntryKindPreference, EntryKindDecision, EntryKindReference}

var _EntryKindNameToValueMap = map[string]EntryKind{
	_EntryKindName[0:11]:       EntryKindUnspecified,
	_EntryKindLowerName[0:11]:  EntryKindUnspecified,
	_EntryKindName[11:15]:      EntryKindFact,
	_EntryKindLowerName[11:15]: EntryKindFact,
	_EntryKindName[15:24]:      EntryKindProcedure,
	_EntryKindLowerName[15:24]: EntryKindProcedure,
	_EntryKindName[24:31]:      EntryKindConcept,
	_EntryKindLowerName[24:31]: EntryKindConcept,
	_EntryKindName[31:38]:      EntryKindWarning,
	_EntryKindLowerName[31:38]: EntryKindWarning,
	_EntryKindName[38:48]:      EntryKindPreference,
	_EntryKindLowerName[38:48]: EntryKindPreference,
	_EntryKindName[48:56]:      EntryKindDecision,
	_EntryKindLowerName[48:56]: EntryKindDecision,
	_EntryKindName[56:65]:      EntryKindReference,
	_EntryKindLowerName[56:65]: EntryKindReference,
}

var _EntryKindNames = []string{
	_EntryKindName[0:11],
	_EntryKindName[11:15],
	_EntryKindName[15:24],
	_EntryKindName[24:31],
	_EntryKindName[31:38],
	_EntryKindName[38:48],
	_EntryKindName[48:56],
	_EntryKindName[56:65],
}

// EntryKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EntryKindString(s string) (EntryKind, error) {
	if val, ok := _EntryKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EntryKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EntryKind values", s)
}

// EntryKindValues returns all values of the enum
func EntryKindValues() []EntryKind {
	return _EntryKindValues
}

// EntryKindStrings returns a slice of all String values of the enum
func EntryKindStrings() []string {
	strs := make([]string, len(_EntryKindNames))
	copy(strs, _EntryKindNames)
	return strs
}

// IsAEntryKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EntryKind) IsAEntryKind() bool {
	for _, v := range _EntryKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EntryKind
func (i EntryKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EntryKind
func (i *EntryKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EntryKind should be a string, got %s", data)
	}

	var err error
	*i, err = EntryKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for EntryKind
func (i EntryKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EntryKind
func (i *EntryKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = EntryKindString(string(text))
	return err
}

const _EntryStateName = "unspecifieddraftactivesupersededarchived"

var _EntryStateIndex = [...]uint8{0, 11, 16, 22, 32, 40}

const _EntryStateLowerName = "unspecifieddraftactivesupersededarchived"

func (i EntryState) String() string {
	if i >= EntryState(len(_EntryStateIndex)-1) {
		return fmt.Sprintf("EntryState(%d)", i)
	}
	return _EntryStateName[_EntryStateIndex[i]:_EntryStateIndex[i+1]]
}

func (EntryState) Values() []string {
	return EntryStateStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EntryStateNoOp() {
	var x [1]struct{}
	_ = x[EntryStateUnspecified-(0)]
	_ = x[EntryStateDraft-(1)]
	_ = x[EntryStateActive-(2)]
	_ = x[EntryStateSuperseded-(3)]
	_ = x[EntryStateArchived-(4)]
}

var _EntryStateValues = []EntryState{EntryStateUnspecified, EntryStateDraft, EntryStateActive, EntryStateSuperseded, EntryStateArchived}

var _EntryStateNameToValueMap = map[string]EntryState{
	_EntryStateName[0:11]:       EntryStateUnspecified,
	_EntryStateLowerName[0:11]:  EntryStateUnspecified,
	_EntryStateName[11:16]:      EntryStateDraft,
	_EntryStateLowerName[11:16]: EntryStateDraft,
	_EntryStateName[16:22]:      EntryStateActive,
	_EntryStateLowerName[16:22]: EntryStateActive,
	_EntryStateName[22:32]:      EntryStateSuperseded,
	_EntryStateLowerName[22:32]: EntryStateSuperseded,
	_EntryStateName[32:40]:      EntryStateArchived,
	_EntryStateLowerName[32:40]: EntryStateArchived,
}

var _EntryStateNames = []string{
	_EntryStateName[0:11],
	_EntryStateName[11:16],
	_EntryStateName[16:22],
	_EntryStateName[22:32],
	_EntryStateName[32:40],
}

// EntryStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EntryStateString(s string) (EntryState, error) {
	if val, ok := _EntryStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EntryStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EntryState values", s)
}

// EntryStateValues returns all values of the enum
func EntryStateValues() []EntryState {
	return _EntryStateValues
}

// EntryStateStrings returns a slice of all String values of the enum
func EntryStateStrings() []string {
	strs := make([]string, len(_EntryStateNames))
	copy(strs, _EntryStateNames)
	return strs
}

// IsAEntryState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EntryState) IsAEntryState() bool {
	for _, v := range _EntryStateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EntryState
func (i EntryState) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EntryState
func (i *EntryState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EntryState should be a string, got %s", data)
	}

	var err error
	*i, err = EntryStateString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for EntryState
func (i EntryState) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EntryState
func (i *EntryState) UnmarshalText(text []byte) error {
	var err error
	*i, err = EntryStateString(string(text))
	return err
}

const _LinkKindName = "unspecifiedrelated_topart_ofrequiresalternative_toapplies_tosupersedescontradictscaused_bysupported_byderived_from"

var _LinkKindIndex = [...]uint8{0, 11, 21, 28, 36, 50, 60, 70, 81, 90, 102, 114}

const _LinkKindLowerName = "unspecifiedrelated_topart_ofrequiresalternative_toapplies_tosupersedescontradictscaused_bysupported_byderived_from"

func (i LinkKind) String() string {
	if i >= LinkKind(len(_LinkKindIndex)-1) {
		return fmt.Sprintf("LinkKind(%d)", i)
	}
	return _LinkKindName[_LinkKindIndex[i]:_LinkKindIndex[i+1]]
}

func (LinkKind) Values() []string {
	return LinkKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LinkKindNoOp() {
	var x [1]struct{}
	_ = x[LinkKindUnspecified-(0)]
	_ = x[LinkKindRelatedTo-(1)]
	_ = x[LinkKindPartOf-(2)]
	_ = x[LinkKindRequires-(3)]
	_ = x[LinkKindAlternativeTo-(4)]
	_ = x[LinkKindAppliesTo-(5)]
	_ = x[LinkKindSupersedes-(6)]
	_ = x[LinkKindContradicts-(7)]
	_ = x[LinkKindCausedBy-(8)]
	_ = x[LinkKindSupportedBy-(9)]
	_ = x[LinkKindDerivedFrom-(10)]
}

var _LinkKindValues = []LinkKind{LinkKindUnspecified, LinkKindRelatedTo, LinkKindPartOf, LinkKindRequires, LinkKindAlternativeTo, LinkKindAppliesTo, LinkKindSupersedes, LinkKindContradicts, LinkKindCausedBy, LinkKindSupportedBy, LinkKindDerivedFrom}

var _LinkKindNameToValueMap = map[string]LinkKind{
	_LinkKindName[0:11]:         LinkKindUnspecified,
	_LinkKindLowerName[0:11]:    LinkKindUnspecified,
	_LinkKindName[11:21]:        LinkKindRelatedTo,
	_LinkKindLowerName[11:21]:   LinkKindRelatedTo,
	_LinkKindName[21:28]:        LinkKindPartOf,
	_LinkKindLowerName[21:28]:   LinkKindPartOf,
	_LinkKindName[28:36]:        LinkKindRequires,
	_LinkKindLowerName[28:36]:   LinkKindRequires,
	_LinkKindName[36:50]:        LinkKindAlternativeTo,
	_LinkKindLowerName[36:50]:   LinkKindAlternativeTo,
	_LinkKindName[50:60]:        LinkKindAppliesTo,
	_LinkKindLowerName[50:60]:   LinkKindAppliesTo,
	_LinkKindName[60:70]:        LinkKindSupersedes,
	_LinkKindLowerName[60:70]:   LinkKindSupersedes,
	_LinkKindName[70:81]:        LinkKindContradicts,
	_LinkKindLowerName[70:81]:   LinkKindContradicts,
	_LinkKindName[81:90]:        LinkKindCausedBy,
	_LinkKindLowerName[81:90]:   LinkKindCausedBy,
	_LinkKindName[90:102]:       LinkKindSupportedBy,
	_LinkKindLowerName[90:102]:  LinkKindSupportedBy,
	_LinkKindName[102:114]:      LinkKindDerivedFrom,
	_LinkKindLowerName[102:114]: LinkKindDerivedFrom,
}

var _LinkKindNames = []string{
	_LinkKindName[0:11],
	_LinkKindName[11:21],
	_LinkKindName[21:28],
	_LinkKindName[28:36],
	_LinkKindName[36:50],
	_LinkKindName[50:60],
	_LinkKindName[60:70],
	_LinkKindName[70:81],
	_LinkKindName[81:90],
	_LinkKindName[90:102],
	_LinkKindName[102:114],
}

// LinkKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LinkKindString(s string) (LinkKind, error) {
	if val, ok := _LinkKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LinkKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LinkKind values", s)
}

// LinkKindValues returns all values of the enum
func LinkKindValues() []LinkKind {
	return _LinkKindValues
}

// LinkKindStrings returns a slice of all String values of the enum
func LinkKindStrings() []string {
	strs := make([]string, len(_LinkKindNames))
	copy(strs, _LinkKindNames)
	return strs
}

// IsALinkKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LinkKind) IsALinkKind() bool {
	for _, v := range _LinkKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for LinkKind
func (i LinkKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for LinkKind
func (i *LinkKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LinkKind should be a string, got %s", data)
	}

	var err error
	*i, err = LinkKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for LinkKind
func (i LinkKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for LinkKind
func (i *LinkKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = LinkKindString(string(text))
	return err
}

const _LinkStateName = "unspecifiedactivearchived"

var _LinkStateIndex = [...]uint8{0, 11, 17, 25}

const _LinkStateLowerName = "unspecifiedactivearchived"

func (i LinkState) String() string {
	if i >= LinkState(len(_LinkStateIndex)-1) {
		return fmt.Sprintf("LinkState(%d)", i)
	}
	return _LinkStateName[_LinkStateIndex[i]:_LinkStateIndex[i+1]]
}

func (LinkState) Values() []string {
	return LinkStateStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LinkStateNoOp() {
	var x [1]struct{}
	_ = x[LinkStateUnspecified-(0)]
	_ = x[LinkStateActive-(1)]
	_ = x[LinkStateArchived-(2)]
}

var _LinkStateValues = []LinkState{LinkStateUnspecified, LinkStateActive, LinkStateArchived}

var _LinkStateNameToValueMap = map[string]LinkState{
	_LinkStateName[0:11]:       LinkStateUnspecified,
	_LinkStateLowerName[0:11]:  LinkStateUnspecified,
	_LinkStateName[11:17]:      LinkStateActive,
	_LinkStateLowerName[11:17]: LinkStateActive,
	_LinkStateName[17:25]:      LinkStateArchived,
	_LinkStateLowerName[17:25]: LinkStateArchived,
}

var _LinkStateNames = []string{
	_LinkStateName[0:11],
	_LinkStateName[11:17],
	_LinkStateName[17:25],
}

// LinkStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LinkStateString(s string) (LinkState, error) {
	if val, ok := _LinkStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LinkStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LinkState values", s)
}

// LinkStateValues returns all values of the enum
func LinkStateValues() []LinkState {
	return _LinkStateValues
}

// LinkStateStrings returns a slice of all String values of the enum
func LinkStateStrings() []string {
	strs := make([]string, len(_LinkStateNames))
	copy(strs, _LinkStateNames)
	return strs
}

// IsALinkState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LinkState) IsALinkState() bool {
	for _, v := range _LinkStateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for LinkState
func (i LinkState) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for LinkState
func (i *LinkState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LinkState should be a string, got %s", data)
	}

	var err error
	*i, err = LinkStateString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for LinkState
func (i LinkState) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for LinkState
func (i *LinkState) UnmarshalText(text []byte) error {
	var err error
	*i, err = LinkStateString(string(text))
	return err
}

const _RiskClassName = "unspecifiedpersonal_sensitivemedicallegalfinancialphysical_safetysecurity_sensitiveprohibited_secret"

var _RiskClassIndex = [...]uint8{0, 11, 29, 36, 41, 50, 65, 83, 100}

const _RiskClassLowerName = "unspecifiedpersonal_sensitivemedicallegalfinancialphysical_safetysecurity_sensitiveprohibited_secret"

func (i RiskClass) String() string {
	if i >= RiskClass(len(_RiskClassIndex)-1) {
		return fmt.Sprintf("RiskClass(%d)", i)
	}
	return _RiskClassName[_RiskClassIndex[i]:_RiskClassIndex[i+1]]
}

func (RiskClass) Values() []string {
	return RiskClassStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RiskClassNoOp() {
	var x [1]struct{}
	_ = x[RiskClassUnspecified-(0)]
	_ = x[RiskClassPersonalSensitive-(1)]
	_ = x[RiskClassMedical-(2)]
	_ = x[RiskClassLegal-(3)]
	_ = x[RiskClassFinancial-(4)]
	_ = x[RiskClassPhysicalSafety-(5)]
	_ = x[RiskClassSecuritySensitive-(6)]
	_ = x[RiskClassProhibitedSecret-(7)]
}

var _RiskClassValues = []RiskClass{RiskClassUnspecified, RiskClassPersonalSensitive, RiskClassMedical, RiskClassLegal, RiskClassFinancial, RiskClassPhysicalSafety, RiskClassSecuritySensitive, RiskClassProhibitedSecret}

var _RiskClassNameToValueMap = map[string]RiskClass{
	_RiskClassName[0:11]:        RiskClassUnspecified,
	_RiskClassLowerName[0:11]:   RiskClassUnspecified,
	_RiskClassName[11:29]:       RiskClassPersonalSensitive,
	_RiskClassLowerName[11:29]:  RiskClassPersonalSensitive,
	_RiskClassName[29:36]:       RiskClassMedical,
	_RiskClassLowerName[29:36]:  RiskClassMedical,
	_RiskClassName[36:41]:       RiskClassLegal,
	_RiskClassLowerName[36:41]:  RiskClassLegal,
	_RiskClassName[41:50]:       RiskClassFinancial,
	_RiskClassLowerName[41:50]:  RiskClassFinancial,
	_RiskClassName[50:65]:       RiskClassPhysicalSafety,
	_RiskClassLowerName[50:65]:  RiskClassPhysicalSafety,
	_RiskClassName[65:83]:       RiskClassSecuritySensitive,
	_RiskClassLowerName[65:83]:  RiskClassSecuritySensitive,
	_RiskClassName[83:100]:      RiskClassProhibitedSecret,
	_RiskClassLowerName[83:100]: RiskClassProhibitedSecret,
}

var _RiskClassNames = []string{
	_RiskClassName[0:11],
	_RiskClassName[11:29],
	_RiskClassName[29:36],
	_RiskClassName[36:41],
	_RiskClassName[41:50],
	_RiskClassName[50:65],
	_RiskClassName[65:83],
	_RiskClassName[83:100],
}

// RiskClassString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RiskClassString(s string) (RiskClass, error) {
	if val, ok := _RiskClassNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RiskClassNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RiskClass values", s)
}

// RiskClassValues returns all values of the enum
func RiskClassValues() []RiskClass {
	return _RiskClassValues
}

// RiskClassStrings returns a slice of all String values of the enum
func RiskClassStrings() []string {
	strs := make([]string, len(_RiskClassNames))
	copy(strs, _RiskClassNames)
	return strs
}

// IsARiskClass returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RiskClass) IsARiskClass() bool {
	for _, v := range _RiskClassValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for RiskClass
func (i RiskClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for RiskClass
func (i *RiskClass) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("RiskClass should be a string, got %s", data)
	}

	var err error
	*i, err = RiskClassString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for RiskClass
func (i RiskClass) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for RiskClass
func (i *RiskClass) UnmarshalText(text []byte) error {
	var err error
	*i, err = RiskClassString(string(text))
	return err
}

const _VerificationStatusName = "unspecifiedunverifiedpartially_verifiedverifieddisputed"

var _VerificationStatusIndex = [...]uint8{0, 11, 21, 39, 47, 55}

const _VerificationStatusLowerName = "unspecifiedunverifiedpartially_verifiedverifieddisputed"

func (i VerificationStatus) String() string {
	if i >= VerificationStatus(len(_VerificationStatusIndex)-1) {
		return fmt.Sprintf("VerificationStatus(%d)", i)
	}
	return _VerificationStatusName[_VerificationStatusIndex[i]:_VerificationStatusIndex[i+1]]
}

func (VerificationStatus) Values() []string {
	return VerificationStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _VerificationStatusNoOp() {
	var x [1]struct{}
	_ = x[VerificationStatusUnspecified-(0)]
	_ = x[VerificationStatusUnverified-(1)]
	_ = x[VerificationStatusPartiallyVerified-(2)]
	_ = x[VerificationStatusVerified-(3)]
	_ = x[VerificationStatusDisputed-(4)]
}

var _VerificationStatusValues = []VerificationStatus{VerificationStatusUnspecified, VerificationStatusUnverified, VerificationStatusPartiallyVerified, VerificationStatusVerified, VerificationStatusDisputed}

var _VerificationStatusNameToValueMap = map[string]VerificationStatus{
	_VerificationStatusName[0:11]:       VerificationStatusUnspecified,
	_VerificationStatusLowerName[0:11]:  VerificationStatusUnspecified,
	_VerificationStatusName[11:21]:      VerificationStatusUnverified,
	_VerificationStatusLowerName[11:21]: VerificationStatusUnverified,
	_VerificationStatusName[21:39]:      VerificationStatusPartiallyVerified,
	_VerificationStatusLowerName[21:39]: VerificationStatusPartiallyVerified,
	_VerificationStatusName[39:47]:      VerificationStatusVerified,
	_VerificationStatusLowerName[39:47]: VerificationStatusVerified,
	_VerificationStatusName[47:55]:      VerificationStatusDisputed,
	_VerificationStatusLowerName[47:55]: VerificationStatusDisputed,
}

var _VerificationStatusNames = []string{
	_VerificationStatusName[0:11],
	_VerificationStatusName[11:21],
	_VerificationStatusName[21:39],
	_VerificationStatusName[39:47],
	_VerificationStatusName[47:55],
}

// VerificationStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func VerificationStatusString(s string) (VerificationStatus, error) {
	if val, ok := _VerificationStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _VerificationStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to VerificationStatus values", s)
}

// VerificationStatusValues returns all values of the enum
func VerificationStatusValues() []VerificationStatus {
	return _VerificationStatusValues
}

// VerificationStatusStrings returns a slice of all String values of the enum
func VerificationStatusStrings() []string {
	strs := make([]string, len(_VerificationStatusNames))
	copy(strs, _VerificationStatusNames)
	return strs
}

// IsAVerificationStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i VerificationStatus) IsAVerificationStatus() bool {
	for _, v := range _VerificationStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for VerificationStatus
func (i VerificationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for VerificationStatus
func (i *VerificationStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("VerificationStatus should be a string, got %s", data)
	}

	var err error
	*i, err = VerificationStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for VerificationStatus
func (i VerificationStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for VerificationStatus
func (i *VerificationStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = VerificationStatusString(string(text))
	return err
}

const _EvidenceTypeName = "unspecifieduser_statementchat_turntool_resultfilewebpackageobservation"

var _EvidenceTypeIndex = [...]uint8{0, 11, 25, 34, 45, 49, 52, 59, 70}

const _EvidenceTypeLowerName = "unspecifieduser_statementchat_turntool_resultfilewebpackageobservation"

func (i EvidenceType) String() string {
	if i >= EvidenceType(len(_EvidenceTypeIndex)-1) {
		return fmt.Sprintf("EvidenceType(%d)", i)
	}
	return _EvidenceTypeName[_EvidenceTypeIndex[i]:_EvidenceTypeIndex[i+1]]
}

func (EvidenceType) Values() []string {
	return EvidenceTypeStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EvidenceTypeNoOp() {
	var x [1]struct{}
	_ = x[EvidenceTypeUnspecified-(0)]
	_ = x[EvidenceTypeUserStatement-(1)]
	_ = x[EvidenceTypeChatTurn-(2)]
	_ = x[EvidenceTypeToolResult-(3)]
	_ = x[EvidenceTypeFile-(4)]
	_ = x[EvidenceTypeWeb-(5)]
	_ = x[EvidenceTypePackage-(6)]
	_ = x[EvidenceTypeObservation-(7)]
}

var _EvidenceTypeValues = []EvidenceType{EvidenceTypeUnspecified, EvidenceTypeUserStatement, EvidenceTypeChatTurn, EvidenceTypeToolResult, EvidenceTypeFile, EvidenceTypeWeb, EvidenceTypePackage, EvidenceTypeObservation}

var _EvidenceTypeNameToValueMap = map[string]EvidenceType{
	_EvidenceTypeName[0:11]:       EvidenceTypeUnspecified,
	_EvidenceTypeLowerName[0:11]:  EvidenceTypeUnspecified,
	_EvidenceTypeName[11:25]:      EvidenceTypeUserStatement,
	_EvidenceTypeLowerName[11:25]: EvidenceTypeUserStatement,
	_EvidenceTypeName[25:34]:      EvidenceTypeChatTurn,
	_EvidenceTypeLowerName[25:34]: EvidenceTypeChatTurn,
	_EvidenceTypeName[34:45]:      EvidenceTypeToolResult,
	_EvidenceTypeLowerName[34:45]: EvidenceTypeToolResult,
	_EvidenceTypeName[45:49]:      EvidenceTypeFile,
	_EvidenceTypeLowerName[45:49]: EvidenceTypeFile,
	_EvidenceTypeName[49:52]:      EvidenceTypeWeb,
	_EvidenceTypeLowerName[49:52]: EvidenceTypeWeb,
	_EvidenceTypeName[52:59]:      EvidenceTypePackage,
	_EvidenceTypeLowerName[52:59]: EvidenceTypePackage,
	_EvidenceTypeName[59:70]:      EvidenceTypeObservation,
	_EvidenceTypeLowerName[59:70]: EvidenceTypeObservation,
}

var _EvidenceTypeNames = []string{
	_EvidenceTypeName[0:11],
	_EvidenceTypeName[11:25],
	_EvidenceTypeName[25:34],
	_EvidenceTypeName[34:45],
	_EvidenceTypeName[45:49],
	_EvidenceTypeName[49:52],
	_EvidenceTypeName[52:59],
	_EvidenceTypeName[59:70],
}

// EvidenceTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EvidenceTypeString(s string) (EvidenceType, error) {
	if val, ok := _EvidenceTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EvidenceTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EvidenceType values", s)
}

// EvidenceTypeValues returns all values of the enum
func EvidenceTypeValues() []EvidenceType {
	return _EvidenceTypeValues
}

// EvidenceTypeStrings returns a slice of all String values of the enum
func EvidenceTypeStrings() []string {
	strs := make([]string, len(_EvidenceTypeNames))
	copy(strs, _EvidenceTypeNames)
	return strs
}

// IsAEvidenceType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EvidenceType) IsAEvidenceType() bool {
	for _, v := range _EvidenceTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EvidenceType
func (i EvidenceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EvidenceType
func (i *EvidenceType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EvidenceType should be a string, got %s", data)
	}

	var err error
	*i, err = EvidenceTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for EvidenceType
func (i EvidenceType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EvidenceType
func (i *EvidenceType) UnmarshalText(text []byte) error {
	var err error
	*i, err = EvidenceTypeString(string(text))
	return err
}

const _EvidenceQualityName = "unspecifiedprimaryauthoritativesecondaryanecdotalgenerated"

var _EvidenceQualityIndex = [...]uint8{0, 11, 18, 31, 40, 49, 58}

const _EvidenceQualityLowerName = "unspecifiedprimaryauthoritativesecondaryanecdotalgenerated"

func (i EvidenceQuality) String() string {
	if i >= EvidenceQuality(len(_EvidenceQualityIndex)-1) {
		return fmt.Sprintf("EvidenceQuality(%d)", i)
	}
	return _EvidenceQualityName[_EvidenceQualityIndex[i]:_EvidenceQualityIndex[i+1]]
}

func (EvidenceQuality) Values() []string {
	return EvidenceQualityStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EvidenceQualityNoOp() {
	var x [1]struct{}
	_ = x[EvidenceQualityUnspecified-(0)]
	_ = x[EvidenceQualityPrimary-(1)]
	_ = x[EvidenceQualityAuthoritative-(2)]
	_ = x[EvidenceQualitySecondary-(3)]
	_ = x[EvidenceQualityAnecdotal-(4)]
	_ = x[EvidenceQualityGenerated-(5)]
}

var _EvidenceQualityValues = []EvidenceQuality{EvidenceQualityUnspecified, EvidenceQualityPrimary, EvidenceQualityAuthoritative, EvidenceQualitySecondary, EvidenceQualityAnecdotal, EvidenceQualityGenerated}

var _EvidenceQualityNameToValueMap = map[string]EvidenceQuality{
	_EvidenceQualityName[0:11]:       EvidenceQualityUnspecified,
	_EvidenceQualityLowerName[0:11]:  EvidenceQualityUnspecified,
	_EvidenceQualityName[11:18]:      EvidenceQualityPrimary,
	_EvidenceQualityLowerName[11:18]: EvidenceQualityPrimary,
	_EvidenceQualityName[18:31]:      EvidenceQualityAuthoritative,
	_EvidenceQualityLowerName[18:31]: EvidenceQualityAuthoritative,
	_EvidenceQualityName[31:40]:      EvidenceQualitySecondary,
	_EvidenceQualityLowerName[31:40]: EvidenceQualitySecondary,
	_EvidenceQualityName[40:49]:      EvidenceQualityAnecdotal,
	_EvidenceQualityLowerName[40:49]: EvidenceQualityAnecdotal,
	_EvidenceQualityName[49:58]:      EvidenceQualityGenerated,
	_EvidenceQualityLowerName[49:58]: EvidenceQualityGenerated,
}

var _EvidenceQualityNames = []string{
	_EvidenceQualityName[0:11],
	_EvidenceQualityName[11:18],
	_EvidenceQualityName[18:31],
	_EvidenceQualityName[31:40],
	_EvidenceQualityName[40:49],
	_EvidenceQualityName[49:58],
}

// EvidenceQualityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EvidenceQualityString(s string) (EvidenceQuality, error) {
	if val, ok := _EvidenceQualityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EvidenceQualityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EvidenceQuality values", s)
}

// EvidenceQualityValues returns all values of the enum
func EvidenceQualityValues() []EvidenceQuality {
	return _EvidenceQualityValues
}

// EvidenceQualityStrings returns a slice of all String values of the enum
func EvidenceQualityStrings() []string {
	strs := make([]string, len(_EvidenceQualityNames))
	copy(strs, _EvidenceQualityNames)
	return strs
}

// IsAEvidenceQuality returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EvidenceQuality) IsAEvidenceQuality() bool {
	for _, v := range _EvidenceQualityValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EvidenceQuality
func (i EvidenceQuality) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EvidenceQuality
func (i *EvidenceQuality) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EvidenceQuality should be a string, got %s", data)
	}

	var err error
	*i, err = EvidenceQualityString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for EvidenceQuality
func (i EvidenceQuality) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EvidenceQuality
func (i *EvidenceQuality) UnmarshalText(text []byte) error {
	var err error
	*i, err = EvidenceQualityString(string(text))
	return err
}

const _PersonalOriginName = "unspecifiedexplicitobservedinferred"

var _PersonalOriginIndex = [...]uint8{0, 11, 19, 27, 35}

const _PersonalOriginLowerName = "unspecifiedexplicitobservedinferred"

func (i PersonalOrigin) String() string {
	if i >= PersonalOrigin(len(_PersonalOriginIndex)-1) {
		return fmt.Sprintf("PersonalOrigin(%d)", i)
	}
	return _PersonalOriginName[_PersonalOriginIndex[i]:_PersonalOriginIndex[i+1]]
}

func (PersonalOrigin) Values() []string {
	return PersonalOriginStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PersonalOriginNoOp() {
	var x [1]struct{}
	_ = x[PersonalOriginUnspecified-(0)]
	_ = x[PersonalOriginExplicit-(1)]
	_ = x[PersonalOriginObserved-(2)]
	_ = x[PersonalOriginInferred-(3)]
}

var _PersonalOriginValues = []PersonalOrigin{PersonalOriginUnspecified, PersonalOriginExplicit, PersonalOriginObserved, PersonalOriginInferred}

var _PersonalOriginNameToValueMap = map[string]PersonalOrigin{
	_PersonalOriginName[0:11]:       PersonalOriginUnspecified,
	_PersonalOriginLowerName[0:11]:  PersonalOriginUnspecified,
	_PersonalOriginName[11:19]:      PersonalOriginExplicit,
	_PersonalOriginLowerName[11:19]: PersonalOriginExplicit,
	_PersonalOriginName[19:27]:      PersonalOriginObserved,
	_PersonalOriginLowerName[19:27]: PersonalOriginObserved,
	_PersonalOriginName[27:35]:      PersonalOriginInferred,
	_PersonalOriginLowerName[27:35]: PersonalOriginInferred,
}

var _PersonalOriginNames = []string{
	_PersonalOriginName[0:11],
	_PersonalOriginName[11:19],
	_PersonalOriginName[19:27],
	_PersonalOriginName[27:35],
}

// PersonalOriginString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PersonalOriginString(s string) (PersonalOrigin, error) {
	if val, ok := _PersonalOriginNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PersonalOriginNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PersonalOrigin values", s)
}

// PersonalOriginValues returns all values of the enum
func PersonalOriginValues() []PersonalOrigin {
	return _PersonalOriginValues
}

// PersonalOriginStrings returns a slice of all String values of the enum
func PersonalOriginStrings() []string {
	strs := make([]string, len(_PersonalOriginNames))
	copy(strs, _PersonalOriginNames)
	return strs
}

// IsAPersonalOrigin returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PersonalOrigin) IsAPersonalOrigin() bool {
	for _, v := range _PersonalOriginValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PersonalOrigin
func (i PersonalOrigin) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PersonalOrigin
func (i *PersonalOrigin) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PersonalOrigin should be a string, got %s", data)
	}

	var err error
	*i, err = PersonalOriginString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for PersonalOrigin
func (i PersonalOrigin) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PersonalOrigin
func (i *PersonalOrigin) UnmarshalText(text []byte) error {
	var err error
	*i, err = PersonalOriginString(string(text))
	return err
}

const _ObjectKindName = "unspecifiedchunkentrylink"

var _ObjectKindIndex = [...]uint8{0, 11, 16, 21, 25}

const _ObjectKindLowerName = "unspecifiedchunkentrylink"

func (i ObjectKind) String() string {
	if i >= ObjectKind(len(_ObjectKindIndex)-1) {
		return fmt.Sprintf("ObjectKind(%d)", i)
	}
	return _ObjectKindName[_ObjectKindIndex[i]:_ObjectKindIndex[i+1]]
}

func (ObjectKind) Values() []string {
	return ObjectKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ObjectKindNoOp() {
	var x [1]struct{}
	_ = x[ObjectKindUnspecified-(0)]
	_ = x[ObjectKindChunk-(1)]
	_ = x[ObjectKindEntry-(2)]
	_ = x[ObjectKindLink-(3)]
}

var _ObjectKindValues = []ObjectKind{ObjectKindUnspecified, ObjectKindChunk, ObjectKindEntry, ObjectKindLink}

var _ObjectKindNameToValueMap = map[string]ObjectKind{
	_ObjectKindName[0:11]:       ObjectKindUnspecified,
	_ObjectKindLowerName[0:11]:  ObjectKindUnspecified,
	_ObjectKindName[11:16]:      ObjectKindChunk,
	_ObjectKindLowerName[11:16]: ObjectKindChunk,
	_ObjectKindName[16:21]:      ObjectKindEntry,
	_ObjectKindLowerName[16:21]: ObjectKindEntry,
	_ObjectKindName[21:25]:      ObjectKindLink,
	_ObjectKindLowerName[21:25]: ObjectKindLink,
}

var _ObjectKindNames = []string{
	_ObjectKindName[0:11],
	_ObjectKindName[11:16],
	_ObjectKindName[16:21],
	_ObjectKindName[21:25],
}

// ObjectKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ObjectKindString(s string) (ObjectKind, error) {
	if val, ok := _ObjectKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ObjectKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ObjectKind values", s)
}

// ObjectKindValues returns all values of the enum
func ObjectKindValues() []ObjectKind {
	return _ObjectKindValues
}

// ObjectKindStrings returns a slice of all String values of the enum
func ObjectKindStrings() []string {
	strs := make([]string, len(_ObjectKindNames))
	copy(strs, _ObjectKindNames)
	return strs
}

// IsAObjectKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ObjectKind) IsAObjectKind() bool {
	for _, v := range _ObjectKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ObjectKind
func (i ObjectKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ObjectKind
func (i *ObjectKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ObjectKind should be a string, got %s", data)
	}

	var err error
	*i, err = ObjectKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ObjectKind
func (i ObjectKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ObjectKind
func (i *ObjectKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = ObjectKindString(string(text))
	return err
}

const _ActorKindName = "unspecifieduserchatsystemimport"

var _ActorKindIndex = [...]uint8{0, 11, 15, 19, 25, 31}

const _ActorKindLowerName = "unspecifieduserchatsystemimport"

func (i ActorKind) String() string {
	if i >= ActorKind(len(_ActorKindIndex)-1) {
		return fmt.Sprintf("ActorKind(%d)", i)
	}
	return _ActorKindName[_ActorKindIndex[i]:_ActorKindIndex[i+1]]
}

func (ActorKind) Values() []string {
	return ActorKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ActorKindNoOp() {
	var x [1]struct{}
	_ = x[ActorKindUnspecified-(0)]
	_ = x[ActorKindUser-(1)]
	_ = x[ActorKindChat-(2)]
	_ = x[ActorKindSystem-(3)]
	_ = x[ActorKindImport-(4)]
}

var _ActorKindValues = []ActorKind{ActorKindUnspecified, ActorKindUser, ActorKindChat, ActorKindSystem, ActorKindImport}

var _ActorKindNameToValueMap = map[string]ActorKind{
	_ActorKindName[0:11]:       ActorKindUnspecified,
	_ActorKindLowerName[0:11]:  ActorKindUnspecified,
	_ActorKindName[11:15]:      ActorKindUser,
	_ActorKindLowerName[11:15]: ActorKindUser,
	_ActorKindName[15:19]:      ActorKindChat,
	_ActorKindLowerName[15:19]: ActorKindChat,
	_ActorKindName[19:25]:      ActorKindSystem,
	_ActorKindLowerName[19:25]: ActorKindSystem,
	_ActorKindName[25:31]:      ActorKindImport,
	_ActorKindLowerName[25:31]: ActorKindImport,
}

var _ActorKindNames = []string{
	_ActorKindName[0:11],
	_ActorKindName[11:15],
	_ActorKindName[15:19],
	_ActorKindName[19:25],
	_ActorKindName[25:31],
}

// ActorKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ActorKindString(s string) (ActorKind, error) {
	if val, ok := _ActorKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ActorKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ActorKind values", s)
}

// ActorKindValues returns all values of the enum
func ActorKindValues() []ActorKind {
	return _ActorKindValues
}

// ActorKindStrings returns a slice of all String values of the enum
func ActorKindStrings() []string {
	strs := make([]string, len(_ActorKindNames))
	copy(strs, _ActorKindNames)
	return strs
}

// IsAActorKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ActorKind) IsAActorKind() bool {
	for _, v := range _ActorKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ActorKind
func (i ActorKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ActorKind
func (i *ActorKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ActorKind should be a string, got %s", data)
	}

	var err error
	*i, err = ActorKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ActorKind
func (i ActorKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ActorKind
func (i *ActorKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = ActorKindString(string(text))
	return err
}
