package com.lkarlslund.koder.voice

import androidx.test.ext.junit.runners.AndroidJUnit4
import java.net.InetAddress
import java.util.Base64
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import mockwebserver3.MockResponse
import mockwebserver3.MockWebServer
import okhttp3.Response
import okhttp3.WebSocket
import okhttp3.WebSocketListener
import okio.ByteString
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class OpusCompatibilityInstrumentedTest {
	@Test
	fun negotiatesOpusAndExchangesPackets() {
		val server = MockWebServer()
		val selected = CountDownLatch(1)
		val receivedInput = CountDownLatch(1)
		val receivedOutput = CountDownLatch(1)
		val socketClosed = CountDownLatch(1)
		val inputFormat = VoiceAudioFormat(VoiceProtocol.OPUS_ENCODING, 16_000, 1)
		val outputFormat = VoiceAudioFormat(VoiceProtocol.OPUS_ENCODING, 24_000, 1)
		server.enqueue(MockResponse.Builder().webSocketUpgrade(object : WebSocketListener() {
			override fun onOpen(webSocket: WebSocket, response: Response) {
				webSocket.send(advertisedReady)
			}

			override fun onMessage(webSocket: WebSocket, text: String) {
				val frame = JSONObject(text)
				if (frame.getString("type") == "hello") {
					assertEquals("opus", frame.getJSONArray("audio_encodings").getString(0))
					webSocket.send(negotiatedReady)
				}
			}

			override fun onMessage(webSocket: WebSocket, bytes: ByteString) {
				val frame = VoiceProtocol.decodeAudio(bytes.toByteArray())
				if (frame.kind != VoiceAudioFrameKind.INPUT_OPUS) return
				assertEquals(640, OpusAudioDecoder(inputFormat).decode(frame.payload).size)
				receivedInput.countDown()
				val goPacket = Base64.getDecoder().decode(GO_GOPUS_24K_PACKET)
				webSocket.send(ByteString.of(*VoiceProtocol.encodeAudio(VoiceAudioFrame(VoiceAudioFrameKind.OUTPUT_OPUS, 0, 0, goPacket))))
			}

			override fun onClosing(webSocket: WebSocket, code: Int, reason: String) {
				webSocket.close(code, reason)
			}

			override fun onClosed(webSocket: WebSocket, code: Int, reason: String) {
				socketClosed.countDown()
			}
		}).build())
		server.start(InetAddress.getByAddress(byteArrayOf(127, 0, 0, 1)), 0)

		val connection = VoiceConnection(object : VoiceConnection.Listener {
			override fun onConnected() = Unit
			override fun onFrame(frame: VoiceServerFrame) {
				if (frame.type == "ready" && frame.audioConfig?.transportSelected() == true) selected.countDown()
			}
			override fun onAudioFrame(frame: VoiceAudioFrame) {
				if (frame.kind == VoiceAudioFrameKind.OUTPUT_OPUS) {
					assertEquals(960, OpusAudioDecoder(outputFormat).decode(frame.payload).size)
					receivedOutput.countDown()
				}
			}
			override fun onDisconnected(reason: String) = Unit
		})
		try {
			connection.connect(server.url("/").toString(), "")
			assertTrue("Opus transport was not selected", selected.await(5, TimeUnit.SECONDS))
			val encoder = OpusAudioEncoder(inputFormat, INPUT_OPUS_BITRATE)
			val packet = encoder.append(ShortArray(320) { 1_000 }).single()
			connection.startAudio(inputFormat)
			connection.sendAudio(0, packet.payload, VoiceAudioFrameKind.INPUT_OPUS, packet.sourcePCMBytes)
			assertTrue("server did not decode input Opus", receivedInput.await(5, TimeUnit.SECONDS))
			assertTrue("client did not decode output Opus", receivedOutput.await(5, TimeUnit.SECONDS))
		} finally {
			connection.close()
			socketClosed.await(5, TimeUnit.SECONDS)
			server.close()
		}
	}

	private companion object {
		val advertisedReady = """{"type":"ready","protocol":"voice.v1","audio_config":{"input":{"encoding":"pcm_s16le","sample_rate":16000,"channels":1},"output":{"encoding":"pcm_s16le","sample_rate":24000,"channels":1},"transport_encodings":["opus","pcm_s16le"],"max_utterance_seconds":60}}"""
		val negotiatedReady = """{"type":"ready","protocol":"voice.v1","audio_config":{"input":{"encoding":"pcm_s16le","sample_rate":16000,"channels":1},"output":{"encoding":"pcm_s16le","sample_rate":24000,"channels":1},"transport_encodings":["opus","pcm_s16le"],"input_transport":{"encoding":"opus","sample_rate":16000,"channels":1},"output_transport":{"encoding":"opus","sample_rate":24000,"channels":1},"max_utterance_seconds":60}}"""
		// A 20 ms mono packet generated by Koder's Go gopus encoder; Opus decodes at the negotiated output rate.
		const val GO_GOPUS_24K_PACKET = "SIK1A2yemawAAARf+DAEigUbAV9h6UiZqPeol1Tp+pMLRk8JOV6m6v1d/9/DJ3pJHoNAJt1q7uIy4j8ufJp0pvhrU3K8"
	}
}
