// Code generated by "enumer -type=LegacyTaskStatus,MilestoneStatus,TaskStatus -trimprefix=LegacyTaskStatus,MilestoneStatus,TaskStatus -transform=snake -json -text -values -output=status_enumer.go"; DO NOT EDIT.

package planning

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _LegacyTaskStatusName = "pendingin_progresscompletedcancelled"

var _LegacyTaskStatusIndex = [...]uint8{0, 7, 18, 27, 36}

const _LegacyTaskStatusLowerName = "pendingin_progresscompletedcancelled"

func (i LegacyTaskStatus) String() string {
	if i >= LegacyTaskStatus(len(_LegacyTaskStatusIndex)-1) {
		return fmt.Sprintf("LegacyTaskStatus(%d)", i)
	}
	return _LegacyTaskStatusName[_LegacyTaskStatusIndex[i]:_LegacyTaskStatusIndex[i+1]]
}

func (LegacyTaskStatus) Values() []string {
	return LegacyTaskStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LegacyTaskStatusNoOp() {
	var x [1]struct{}
	_ = x[LegacyTaskStatusPending-(0)]
	_ = x[LegacyTaskStatusInProgress-(1)]
	_ = x[LegacyTaskStatusCompleted-(2)]
	_ = x[LegacyTaskStatusCancelled-(3)]
}

var _LegacyTaskStatusValues = []LegacyTaskStatus{LegacyTaskStatusPending, LegacyTaskStatusInProgress, LegacyTaskStatusCompleted, LegacyTaskStatusCancelled}

var _LegacyTaskStatusNameToValueMap = map[string]LegacyTaskStatus{
	_LegacyTaskStatusName[0:7]:        LegacyTaskStatusPending,
	_LegacyTaskStatusLowerName[0:7]:   LegacyTaskStatusPending,
	_LegacyTaskStatusName[7:18]:       LegacyTaskStatusInProgress,
	_LegacyTaskStatusLowerName[7:18]:  LegacyTaskStatusInProgress,
	_LegacyTaskStatusName[18:27]:      LegacyTaskStatusCompleted,
	_LegacyTaskStatusLowerName[18:27]: LegacyTaskStatusCompleted,
	_LegacyTaskStatusName[27:36]:      LegacyTaskStatusCancelled,
	_LegacyTaskStatusLowerName[27:36]: LegacyTaskStatusCancelled,
}

var _LegacyTaskStatusNames = []string{
	_LegacyTaskStatusName[0:7],
	_LegacyTaskStatusName[7:18],
	_LegacyTaskStatusName[18:27],
	_LegacyTaskStatusName[27:36],
}

// LegacyTaskStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LegacyTaskStatusString(s string) (LegacyTaskStatus, error) {
	if val, ok := _LegacyTaskStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LegacyTaskStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LegacyTaskStatus values", s)
}

// LegacyTaskStatusValues returns all values of the enum
func LegacyTaskStatusValues() []LegacyTaskStatus {
	return _LegacyTaskStatusValues
}

// LegacyTaskStatusStrings returns a slice of all String values of the enum
func LegacyTaskStatusStrings() []string {
	strs := make([]string, len(_LegacyTaskStatusNames))
	copy(strs, _LegacyTaskStatusNames)
	return strs
}

// IsALegacyTaskStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LegacyTaskStatus) IsALegacyTaskStatus() bool {
	for _, v := range _LegacyTaskStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for LegacyTaskStatus
func (i LegacyTaskStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for LegacyTaskStatus
func (i *LegacyTaskStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LegacyTaskStatus should be a string, got %s", data)
	}

	var err error
	*i, err = LegacyTaskStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for LegacyTaskStatus
func (i LegacyTaskStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for LegacyTaskStatus
func (i *LegacyTaskStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = LegacyTaskStatusString(string(text))
	return err
}

const _MilestoneStatusName = "pendingdecomposingreadyexecutingcompletedblockedcancelled"

var _MilestoneStatusIndex = [...]uint8{0, 7, 18, 23, 32, 41, 48, 57}

const _MilestoneStatusLowerName = "pendingdecomposingreadyexecutingcompletedblockedcancelled"

func (i MilestoneStatus) String() string {
	if i >= MilestoneStatus(len(_MilestoneStatusIndex)-1) {
		return fmt.Sprintf("MilestoneStatus(%d)", i)
	}
	return _MilestoneStatusName[_MilestoneStatusIndex[i]:_MilestoneStatusIndex[i+1]]
}

func (MilestoneStatus) Values() []string {
	return MilestoneStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MilestoneStatusNoOp() {
	var x [1]struct{}
	_ = x[MilestoneStatusPending-(0)]
	_ = x[MilestoneStatusDecomposing-(1)]
	_ = x[MilestoneStatusReady-(2)]
	_ = x[MilestoneStatusExecuting-(3)]
	_ = x[MilestoneStatusCompleted-(4)]
	_ = x[MilestoneStatusBlocked-(5)]
	_ = x[MilestoneStatusCancelled-(6)]
}

var _MilestoneStatusValues = []MilestoneStatus{MilestoneStatusPending, MilestoneStatusDecomposing, MilestoneStatusReady, MilestoneStatusExecuting, MilestoneStatusCompleted, MilestoneStatusBlocked, MilestoneStatusCancelled}

var _MilestoneStatusNameToValueMap = map[string]MilestoneStatus{
	_MilestoneStatusName[0:7]:        MilestoneStatusPending,
	_MilestoneStatusLowerName[0:7]:   MilestoneStatusPending,
	_MilestoneStatusName[7:18]:       MilestoneStatusDecomposing,
	_MilestoneStatusLowerName[7:18]:  MilestoneStatusDecomposing,
	_MilestoneStatusName[18:23]:      MilestoneStatusReady,
	_MilestoneStatusLowerName[18:23]: MilestoneStatusReady,
	_MilestoneStatusName[23:32]:      MilestoneStatusExecuting,
	_MilestoneStatusLowerName[23:32]: MilestoneStatusExecuting,
	_MilestoneStatusName[32:41]:      MilestoneStatusCompleted,
	_MilestoneStatusLowerName[32:41]: MilestoneStatusCompleted,
	_MilestoneStatusName[41:48]:      MilestoneStatusBlocked,
	_MilestoneStatusLowerName[41:48]: MilestoneStatusBlocked,
	_MilestoneStatusName[48:57]:      MilestoneStatusCancelled,
	_MilestoneStatusLowerName[48:57]: MilestoneStatusCancelled,
}

var _MilestoneStatusNames = []string{
	_MilestoneStatusName[0:7],
	_MilestoneStatusName[7:18],
	_MilestoneStatusName[18:23],
	_MilestoneStatusName[23:32],
	_MilestoneStatusName[32:41],
	_MilestoneStatusName[41:48],
	_MilestoneStatusName[48:57],
}

// MilestoneStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MilestoneStatusString(s string) (MilestoneStatus, error) {
	if val, ok := _MilestoneStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MilestoneStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MilestoneStatus values", s)
}

// MilestoneStatusValues returns all values of the enum
func MilestoneStatusValues() []MilestoneStatus {
	return _MilestoneStatusValues
}

// MilestoneStatusStrings returns a slice of all String values of the enum
func MilestoneStatusStrings() []string {
	strs := make([]string, len(_MilestoneStatusNames))
	copy(strs, _MilestoneStatusNames)
	return strs
}

// IsAMilestoneStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MilestoneStatus) IsAMilestoneStatus() bool {
	for _, v := range _MilestoneStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MilestoneStatus
func (i MilestoneStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MilestoneStatus
func (i *MilestoneStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MilestoneStatus should be a string, got %s", data)
	}

	var err error
	*i, err = MilestoneStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for MilestoneStatus
func (i MilestoneStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for MilestoneStatus
func (i *MilestoneStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = MilestoneStatusString(string(text))
	return err
}

const _TaskStatusName = "pendingin_progresscompletedcancelled"

var _TaskStatusIndex = [...]uint8{0, 7, 18, 27, 36}

const _TaskStatusLowerName = "pendingin_progresscompletedcancelled"

func (i TaskStatus) String() string {
	if i >= TaskStatus(len(_TaskStatusIndex)-1) {
		return fmt.Sprintf("TaskStatus(%d)", i)
	}
	return _TaskStatusName[_TaskStatusIndex[i]:_TaskStatusIndex[i+1]]
}

func (TaskStatus) Values() []string {
	return TaskStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TaskStatusNoOp() {
	var x [1]struct{}
	_ = x[TaskStatusPending-(0)]
	_ = x[TaskStatusInProgress-(1)]
	_ = x[TaskStatusCompleted-(2)]
	_ = x[TaskStatusCancelled-(3)]
}

var _TaskStatusValues = []TaskStatus{TaskStatusPending, TaskStatusInProgress, TaskStatusCompleted, TaskStatusCancelled}

var _TaskStatusNameToValueMap = map[string]TaskStatus{
	_TaskStatusName[0:7]:        TaskStatusPending,
	_TaskStatusLowerName[0:7]:   TaskStatusPending,
	_TaskStatusName[7:18]:       TaskStatusInProgress,
	_TaskStatusLowerName[7:18]:  TaskStatusInProgress,
	_TaskStatusName[18:27]:      TaskStatusCompleted,
	_TaskStatusLowerName[18:27]: TaskStatusCompleted,
	_TaskStatusName[27:36]:      TaskStatusCancelled,
	_TaskStatusLowerName[27:36]: TaskStatusCancelled,
}

var _TaskStatusNames = []string{
	_TaskStatusName[0:7],
	_TaskStatusName[7:18],
	_TaskStatusName[18:27],
	_TaskStatusName[27:36],
}

// TaskStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TaskStatusString(s string) (TaskStatus, error) {
	if val, ok := _TaskStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TaskStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TaskStatus values", s)
}

// TaskStatusValues returns all values of the enum
func TaskStatusValues() []TaskStatus {
	return _TaskStatusValues
}

// TaskStatusStrings returns a slice of all String values of the enum
func TaskStatusStrings() []string {
	strs := make([]string, len(_TaskStatusNames))
	copy(strs, _TaskStatusNames)
	return strs
}

// IsATaskStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TaskStatus) IsATaskStatus() bool {
	for _, v := range _TaskStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TaskStatus
func (i TaskStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TaskStatus
func (i *TaskStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TaskStatus should be a string, got %s", data)
	}

	var err error
	*i, err = TaskStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TaskStatus
func (i TaskStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TaskStatus
func (i *TaskStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = TaskStatusString(string(text))
	return err
}
