// Code generated by "enumer -type=PermissionMode -trimprefix=PermissionMode -transform=snake -json -text -values -output=permission_enumer.go"; DO NOT EDIT.

package accesssettings

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PermissionModeName = "allowaskdeny"

var _PermissionModeIndex = [...]uint8{0, 5, 8, 12}

const _PermissionModeLowerName = "allowaskdeny"

func (i PermissionMode) String() string {
	if i >= PermissionMode(len(_PermissionModeIndex)-1) {
		return fmt.Sprintf("PermissionMode(%d)", i)
	}
	return _PermissionModeName[_PermissionModeIndex[i]:_PermissionModeIndex[i+1]]
}

func (PermissionMode) Values() []string {
	return PermissionModeStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PermissionModeNoOp() {
	var x [1]struct{}
	_ = x[PermissionModeAllow-(0)]
	_ = x[PermissionModeAsk-(1)]
	_ = x[PermissionModeDeny-(2)]
}

var _PermissionModeValues = []PermissionMode{PermissionModeAllow, PermissionModeAsk, PermissionModeDeny}

var _PermissionModeNameToValueMap = map[string]PermissionMode{
	_PermissionModeName[0:5]:       PermissionModeAllow,
	_PermissionModeLowerName[0:5]:  PermissionModeAllow,
	_PermissionModeName[5:8]:       PermissionModeAsk,
	_PermissionModeLowerName[5:8]:  PermissionModeAsk,
	_PermissionModeName[8:12]:      PermissionModeDeny,
	_PermissionModeLowerName[8:12]: PermissionModeDeny,
}

var _PermissionModeNames = []string{
	_PermissionModeName[0:5],
	_PermissionModeName[5:8],
	_PermissionModeName[8:12],
}

// PermissionModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PermissionModeString(s string) (PermissionMode, error) {
	if val, ok := _PermissionModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PermissionModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PermissionMode values", s)
}

// PermissionModeValues returns all values of the enum
func PermissionModeValues() []PermissionMode {
	return _PermissionModeValues
}

// PermissionModeStrings returns a slice of all String values of the enum
func PermissionModeStrings() []string {
	strs := make([]string, len(_PermissionModeNames))
	copy(strs, _PermissionModeNames)
	return strs
}

// IsAPermissionMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PermissionMode) IsAPermissionMode() bool {
	for _, v := range _PermissionModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PermissionMode
func (i PermissionMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PermissionMode
func (i *PermissionMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PermissionMode should be a string, got %s", data)
	}

	var err error
	*i, err = PermissionModeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for PermissionMode
func (i PermissionMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PermissionMode
func (i *PermissionMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = PermissionModeString(string(text))
	return err
}
