// Code generated by "enumer -type=MessageRole,PartKind,ApprovalStatus,TaskStatus,MilestoneStatus,TodoStatus,EventKind,QueuedInputKind -trimprefix=MessageRole,PartKind,ApprovalStatus,TaskStatus,MilestoneStatus,TodoStatus,EventKind,QueuedInputKind -transform=snake -json -text -values -output=messagerole_enumer.go"; DO NOT EDIT.

package domain

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MessageRoleName = "systemuserassistanttool"

var _MessageRoleIndex = [...]uint8{0, 6, 10, 19, 23}

const _MessageRoleLowerName = "systemuserassistanttool"

func (i MessageRole) String() string {
	if i >= MessageRole(len(_MessageRoleIndex)-1) {
		return fmt.Sprintf("MessageRole(%d)", i)
	}
	return _MessageRoleName[_MessageRoleIndex[i]:_MessageRoleIndex[i+1]]
}

func (MessageRole) Values() []string {
	return MessageRoleStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MessageRoleNoOp() {
	var x [1]struct{}
	_ = x[MessageRoleSystem-(0)]
	_ = x[MessageRoleUser-(1)]
	_ = x[MessageRoleAssistant-(2)]
	_ = x[MessageRoleTool-(3)]
}

var _MessageRoleValues = []MessageRole{MessageRoleSystem, MessageRoleUser, MessageRoleAssistant, MessageRoleTool}

var _MessageRoleNameToValueMap = map[string]MessageRole{
	_MessageRoleName[0:6]:        MessageRoleSystem,
	_MessageRoleLowerName[0:6]:   MessageRoleSystem,
	_MessageRoleName[6:10]:       MessageRoleUser,
	_MessageRoleLowerName[6:10]:  MessageRoleUser,
	_MessageRoleName[10:19]:      MessageRoleAssistant,
	_MessageRoleLowerName[10:19]: MessageRoleAssistant,
	_MessageRoleName[19:23]:      MessageRoleTool,
	_MessageRoleLowerName[19:23]: MessageRoleTool,
}

var _MessageRoleNames = []string{
	_MessageRoleName[0:6],
	_MessageRoleName[6:10],
	_MessageRoleName[10:19],
	_MessageRoleName[19:23],
}

// MessageRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MessageRoleString(s string) (MessageRole, error) {
	if val, ok := _MessageRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MessageRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MessageRole values", s)
}

// MessageRoleValues returns all values of the enum
func MessageRoleValues() []MessageRole {
	return _MessageRoleValues
}

// MessageRoleStrings returns a slice of all String values of the enum
func MessageRoleStrings() []string {
	strs := make([]string, len(_MessageRoleNames))
	copy(strs, _MessageRoleNames)
	return strs
}

// IsAMessageRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MessageRole) IsAMessageRole() bool {
	for _, v := range _MessageRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MessageRole
func (i MessageRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MessageRole
func (i *MessageRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MessageRole should be a string, got %s", data)
	}

	var err error
	*i, err = MessageRoleString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for MessageRole
func (i MessageRole) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for MessageRole
func (i *MessageRole) UnmarshalText(text []byte) error {
	var err error
	*i, err = MessageRoleString(string(text))
	return err
}

const _PartKindName = "textattachmentreferencereasoningtool_calltool_outputcompactionapproval_requestquestiontask_updateplan_updateusagesystem_noticeevent_notice"

var _PartKindIndex = [...]uint8{0, 4, 14, 23, 32, 41, 52, 62, 78, 86, 97, 108, 113, 126, 138}

const _PartKindLowerName = "textattachmentreferencereasoningtool_calltool_outputcompactionapproval_requestquestiontask_updateplan_updateusagesystem_noticeevent_notice"

func (i PartKind) String() string {
	if i >= PartKind(len(_PartKindIndex)-1) {
		return fmt.Sprintf("PartKind(%d)", i)
	}
	return _PartKindName[_PartKindIndex[i]:_PartKindIndex[i+1]]
}

func (PartKind) Values() []string {
	return PartKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PartKindNoOp() {
	var x [1]struct{}
	_ = x[PartKindText-(0)]
	_ = x[PartKindAttachment-(1)]
	_ = x[PartKindReference-(2)]
	_ = x[PartKindReasoning-(3)]
	_ = x[PartKindToolCall-(4)]
	_ = x[PartKindToolOutput-(5)]
	_ = x[PartKindCompaction-(6)]
	_ = x[PartKindApprovalRequest-(7)]
	_ = x[PartKindQuestion-(8)]
	_ = x[PartKindTaskUpdate-(9)]
	_ = x[PartKindPlanUpdate-(10)]
	_ = x[PartKindUsage-(11)]
	_ = x[PartKindSystemNotice-(12)]
	_ = x[PartKindEventNotice-(13)]
}

var _PartKindValues = []PartKind{PartKindText, PartKindAttachment, PartKindReference, PartKindReasoning, PartKindToolCall, PartKindToolOutput, PartKindCompaction, PartKindApprovalRequest, PartKindQuestion, PartKindTaskUpdate, PartKindPlanUpdate, PartKindUsage, PartKindSystemNotice, PartKindEventNotice}

var _PartKindNameToValueMap = map[string]PartKind{
	_PartKindName[0:4]:          PartKindText,
	_PartKindLowerName[0:4]:     PartKindText,
	_PartKindName[4:14]:         PartKindAttachment,
	_PartKindLowerName[4:14]:    PartKindAttachment,
	_PartKindName[14:23]:        PartKindReference,
	_PartKindLowerName[14:23]:   PartKindReference,
	_PartKindName[23:32]:        PartKindReasoning,
	_PartKindLowerName[23:32]:   PartKindReasoning,
	_PartKindName[32:41]:        PartKindToolCall,
	_PartKindLowerName[32:41]:   PartKindToolCall,
	_PartKindName[41:52]:        PartKindToolOutput,
	_PartKindLowerName[41:52]:   PartKindToolOutput,
	_PartKindName[52:62]:        PartKindCompaction,
	_PartKindLowerName[52:62]:   PartKindCompaction,
	_PartKindName[62:78]:        PartKindApprovalRequest,
	_PartKindLowerName[62:78]:   PartKindApprovalRequest,
	_PartKindName[78:86]:        PartKindQuestion,
	_PartKindLowerName[78:86]:   PartKindQuestion,
	_PartKindName[86:97]:        PartKindTaskUpdate,
	_PartKindLowerName[86:97]:   PartKindTaskUpdate,
	_PartKindName[97:108]:       PartKindPlanUpdate,
	_PartKindLowerName[97:108]:  PartKindPlanUpdate,
	_PartKindName[108:113]:      PartKindUsage,
	_PartKindLowerName[108:113]: PartKindUsage,
	_PartKindName[113:126]:      PartKindSystemNotice,
	_PartKindLowerName[113:126]: PartKindSystemNotice,
	_PartKindName[126:138]:      PartKindEventNotice,
	_PartKindLowerName[126:138]: PartKindEventNotice,
}

var _PartKindNames = []string{
	_PartKindName[0:4],
	_PartKindName[4:14],
	_PartKindName[14:23],
	_PartKindName[23:32],
	_PartKindName[32:41],
	_PartKindName[41:52],
	_PartKindName[52:62],
	_PartKindName[62:78],
	_PartKindName[78:86],
	_PartKindName[86:97],
	_PartKindName[97:108],
	_PartKindName[108:113],
	_PartKindName[113:126],
	_PartKindName[126:138],
}

// PartKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PartKindString(s string) (PartKind, error) {
	if val, ok := _PartKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PartKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PartKind values", s)
}

// PartKindValues returns all values of the enum
func PartKindValues() []PartKind {
	return _PartKindValues
}

// PartKindStrings returns a slice of all String values of the enum
func PartKindStrings() []string {
	strs := make([]string, len(_PartKindNames))
	copy(strs, _PartKindNames)
	return strs
}

// IsAPartKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PartKind) IsAPartKind() bool {
	for _, v := range _PartKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PartKind
func (i PartKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PartKind
func (i *PartKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PartKind should be a string, got %s", data)
	}

	var err error
	*i, err = PartKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for PartKind
func (i PartKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PartKind
func (i *PartKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = PartKindString(string(text))
	return err
}

const _ApprovalStatusName = "pendingapproveddenied"

var _ApprovalStatusIndex = [...]uint8{0, 7, 15, 21}

const _ApprovalStatusLowerName = "pendingapproveddenied"

func (i ApprovalStatus) String() string {
	if i >= ApprovalStatus(len(_ApprovalStatusIndex)-1) {
		return fmt.Sprintf("ApprovalStatus(%d)", i)
	}
	return _ApprovalStatusName[_ApprovalStatusIndex[i]:_ApprovalStatusIndex[i+1]]
}

func (ApprovalStatus) Values() []string {
	return ApprovalStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ApprovalStatusNoOp() {
	var x [1]struct{}
	_ = x[ApprovalStatusPending-(0)]
	_ = x[ApprovalStatusApproved-(1)]
	_ = x[ApprovalStatusDenied-(2)]
}

var _ApprovalStatusValues = []ApprovalStatus{ApprovalStatusPending, ApprovalStatusApproved, ApprovalStatusDenied}

var _ApprovalStatusNameToValueMap = map[string]ApprovalStatus{
	_ApprovalStatusName[0:7]:        ApprovalStatusPending,
	_ApprovalStatusLowerName[0:7]:   ApprovalStatusPending,
	_ApprovalStatusName[7:15]:       ApprovalStatusApproved,
	_ApprovalStatusLowerName[7:15]:  ApprovalStatusApproved,
	_ApprovalStatusName[15:21]:      ApprovalStatusDenied,
	_ApprovalStatusLowerName[15:21]: ApprovalStatusDenied,
}

var _ApprovalStatusNames = []string{
	_ApprovalStatusName[0:7],
	_ApprovalStatusName[7:15],
	_ApprovalStatusName[15:21],
}

// ApprovalStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ApprovalStatusString(s string) (ApprovalStatus, error) {
	if val, ok := _ApprovalStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ApprovalStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ApprovalStatus values", s)
}

// ApprovalStatusValues returns all values of the enum
func ApprovalStatusValues() []ApprovalStatus {
	return _ApprovalStatusValues
}

// ApprovalStatusStrings returns a slice of all String values of the enum
func ApprovalStatusStrings() []string {
	strs := make([]string, len(_ApprovalStatusNames))
	copy(strs, _ApprovalStatusNames)
	return strs
}

// IsAApprovalStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ApprovalStatus) IsAApprovalStatus() bool {
	for _, v := range _ApprovalStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ApprovalStatus
func (i ApprovalStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ApprovalStatus
func (i *ApprovalStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ApprovalStatus should be a string, got %s", data)
	}

	var err error
	*i, err = ApprovalStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ApprovalStatus
func (i ApprovalStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ApprovalStatus
func (i *ApprovalStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = ApprovalStatusString(string(text))
	return err
}

const _TaskStatusName = "pendingin_progresscompletedcancelled"

var _TaskStatusIndex = [...]uint8{0, 7, 18, 27, 36}

const _TaskStatusLowerName = "pendingin_progresscompletedcancelled"

func (i TaskStatus) String() string {
	if i >= TaskStatus(len(_TaskStatusIndex)-1) {
		return fmt.Sprintf("TaskStatus(%d)", i)
	}
	return _TaskStatusName[_TaskStatusIndex[i]:_TaskStatusIndex[i+1]]
}

func (TaskStatus) Values() []string {
	return TaskStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TaskStatusNoOp() {
	var x [1]struct{}
	_ = x[TaskStatusPending-(0)]
	_ = x[TaskStatusInProgress-(1)]
	_ = x[TaskStatusCompleted-(2)]
	_ = x[TaskStatusCancelled-(3)]
}

var _TaskStatusValues = []TaskStatus{TaskStatusPending, TaskStatusInProgress, TaskStatusCompleted, TaskStatusCancelled}

var _TaskStatusNameToValueMap = map[string]TaskStatus{
	_TaskStatusName[0:7]:        TaskStatusPending,
	_TaskStatusLowerName[0:7]:   TaskStatusPending,
	_TaskStatusName[7:18]:       TaskStatusInProgress,
	_TaskStatusLowerName[7:18]:  TaskStatusInProgress,
	_TaskStatusName[18:27]:      TaskStatusCompleted,
	_TaskStatusLowerName[18:27]: TaskStatusCompleted,
	_TaskStatusName[27:36]:      TaskStatusCancelled,
	_TaskStatusLowerName[27:36]: TaskStatusCancelled,
}

var _TaskStatusNames = []string{
	_TaskStatusName[0:7],
	_TaskStatusName[7:18],
	_TaskStatusName[18:27],
	_TaskStatusName[27:36],
}

// TaskStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TaskStatusString(s string) (TaskStatus, error) {
	if val, ok := _TaskStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TaskStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TaskStatus values", s)
}

// TaskStatusValues returns all values of the enum
func TaskStatusValues() []TaskStatus {
	return _TaskStatusValues
}

// TaskStatusStrings returns a slice of all String values of the enum
func TaskStatusStrings() []string {
	strs := make([]string, len(_TaskStatusNames))
	copy(strs, _TaskStatusNames)
	return strs
}

// IsATaskStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TaskStatus) IsATaskStatus() bool {
	for _, v := range _TaskStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TaskStatus
func (i TaskStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TaskStatus
func (i *TaskStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TaskStatus should be a string, got %s", data)
	}

	var err error
	*i, err = TaskStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TaskStatus
func (i TaskStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TaskStatus
func (i *TaskStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = TaskStatusString(string(text))
	return err
}

const _MilestoneStatusName = "pendingdecomposingreadyexecutingcompletedblockedcancelled"

var _MilestoneStatusIndex = [...]uint8{0, 7, 18, 23, 32, 41, 48, 57}

const _MilestoneStatusLowerName = "pendingdecomposingreadyexecutingcompletedblockedcancelled"

func (i MilestoneStatus) String() string {
	if i >= MilestoneStatus(len(_MilestoneStatusIndex)-1) {
		return fmt.Sprintf("MilestoneStatus(%d)", i)
	}
	return _MilestoneStatusName[_MilestoneStatusIndex[i]:_MilestoneStatusIndex[i+1]]
}

func (MilestoneStatus) Values() []string {
	return MilestoneStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MilestoneStatusNoOp() {
	var x [1]struct{}
	_ = x[MilestoneStatusPending-(0)]
	_ = x[MilestoneStatusDecomposing-(1)]
	_ = x[MilestoneStatusReady-(2)]
	_ = x[MilestoneStatusExecuting-(3)]
	_ = x[MilestoneStatusCompleted-(4)]
	_ = x[MilestoneStatusBlocked-(5)]
	_ = x[MilestoneStatusCancelled-(6)]
}

var _MilestoneStatusValues = []MilestoneStatus{MilestoneStatusPending, MilestoneStatusDecomposing, MilestoneStatusReady, MilestoneStatusExecuting, MilestoneStatusCompleted, MilestoneStatusBlocked, MilestoneStatusCancelled}

var _MilestoneStatusNameToValueMap = map[string]MilestoneStatus{
	_MilestoneStatusName[0:7]:        MilestoneStatusPending,
	_MilestoneStatusLowerName[0:7]:   MilestoneStatusPending,
	_MilestoneStatusName[7:18]:       MilestoneStatusDecomposing,
	_MilestoneStatusLowerName[7:18]:  MilestoneStatusDecomposing,
	_MilestoneStatusName[18:23]:      MilestoneStatusReady,
	_MilestoneStatusLowerName[18:23]: MilestoneStatusReady,
	_MilestoneStatusName[23:32]:      MilestoneStatusExecuting,
	_MilestoneStatusLowerName[23:32]: MilestoneStatusExecuting,
	_MilestoneStatusName[32:41]:      MilestoneStatusCompleted,
	_MilestoneStatusLowerName[32:41]: MilestoneStatusCompleted,
	_MilestoneStatusName[41:48]:      MilestoneStatusBlocked,
	_MilestoneStatusLowerName[41:48]: MilestoneStatusBlocked,
	_MilestoneStatusName[48:57]:      MilestoneStatusCancelled,
	_MilestoneStatusLowerName[48:57]: MilestoneStatusCancelled,
}

var _MilestoneStatusNames = []string{
	_MilestoneStatusName[0:7],
	_MilestoneStatusName[7:18],
	_MilestoneStatusName[18:23],
	_MilestoneStatusName[23:32],
	_MilestoneStatusName[32:41],
	_MilestoneStatusName[41:48],
	_MilestoneStatusName[48:57],
}

// MilestoneStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MilestoneStatusString(s string) (MilestoneStatus, error) {
	if val, ok := _MilestoneStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MilestoneStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MilestoneStatus values", s)
}

// MilestoneStatusValues returns all values of the enum
func MilestoneStatusValues() []MilestoneStatus {
	return _MilestoneStatusValues
}

// MilestoneStatusStrings returns a slice of all String values of the enum
func MilestoneStatusStrings() []string {
	strs := make([]string, len(_MilestoneStatusNames))
	copy(strs, _MilestoneStatusNames)
	return strs
}

// IsAMilestoneStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MilestoneStatus) IsAMilestoneStatus() bool {
	for _, v := range _MilestoneStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MilestoneStatus
func (i MilestoneStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MilestoneStatus
func (i *MilestoneStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MilestoneStatus should be a string, got %s", data)
	}

	var err error
	*i, err = MilestoneStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for MilestoneStatus
func (i MilestoneStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for MilestoneStatus
func (i *MilestoneStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = MilestoneStatusString(string(text))
	return err
}

const _TodoStatusName = "pendingin_progresscompleted"

var _TodoStatusIndex = [...]uint8{0, 7, 18, 27}

const _TodoStatusLowerName = "pendingin_progresscompleted"

func (i TodoStatus) String() string {
	if i >= TodoStatus(len(_TodoStatusIndex)-1) {
		return fmt.Sprintf("TodoStatus(%d)", i)
	}
	return _TodoStatusName[_TodoStatusIndex[i]:_TodoStatusIndex[i+1]]
}

func (TodoStatus) Values() []string {
	return TodoStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TodoStatusNoOp() {
	var x [1]struct{}
	_ = x[TodoStatusPending-(0)]
	_ = x[TodoStatusInProgress-(1)]
	_ = x[TodoStatusCompleted-(2)]
}

var _TodoStatusValues = []TodoStatus{TodoStatusPending, TodoStatusInProgress, TodoStatusCompleted}

var _TodoStatusNameToValueMap = map[string]TodoStatus{
	_TodoStatusName[0:7]:        TodoStatusPending,
	_TodoStatusLowerName[0:7]:   TodoStatusPending,
	_TodoStatusName[7:18]:       TodoStatusInProgress,
	_TodoStatusLowerName[7:18]:  TodoStatusInProgress,
	_TodoStatusName[18:27]:      TodoStatusCompleted,
	_TodoStatusLowerName[18:27]: TodoStatusCompleted,
}

var _TodoStatusNames = []string{
	_TodoStatusName[0:7],
	_TodoStatusName[7:18],
	_TodoStatusName[18:27],
}

// TodoStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TodoStatusString(s string) (TodoStatus, error) {
	if val, ok := _TodoStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TodoStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TodoStatus values", s)
}

// TodoStatusValues returns all values of the enum
func TodoStatusValues() []TodoStatus {
	return _TodoStatusValues
}

// TodoStatusStrings returns a slice of all String values of the enum
func TodoStatusStrings() []string {
	strs := make([]string, len(_TodoStatusNames))
	copy(strs, _TodoStatusNames)
	return strs
}

// IsATodoStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TodoStatus) IsATodoStatus() bool {
	for _, v := range _TodoStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TodoStatus
func (i TodoStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TodoStatus
func (i *TodoStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TodoStatus should be a string, got %s", data)
	}

	var err error
	*i, err = TodoStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TodoStatus
func (i TodoStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TodoStatus
func (i *TodoStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = TodoStatusString(string(text))
	return err
}

const _EventKindName = "message_deltamessage_donereasoningtool_call_deltausagetool_starttool_resultapproval_askapproval_replytask_updatesession_titlechat_titleerrorstatus"

var _EventKindIndex = [...]uint8{0, 13, 25, 34, 49, 54, 64, 75, 87, 101, 112, 125, 135, 140, 146}

const _EventKindLowerName = "message_deltamessage_donereasoningtool_call_deltausagetool_starttool_resultapproval_askapproval_replytask_updatesession_titlechat_titleerrorstatus"

func (i EventKind) String() string {
	if i >= EventKind(len(_EventKindIndex)-1) {
		return fmt.Sprintf("EventKind(%d)", i)
	}
	return _EventKindName[_EventKindIndex[i]:_EventKindIndex[i+1]]
}

func (EventKind) Values() []string {
	return EventKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EventKindNoOp() {
	var x [1]struct{}
	_ = x[EventKindMessageDelta-(0)]
	_ = x[EventKindMessageDone-(1)]
	_ = x[EventKindReasoning-(2)]
	_ = x[EventKindToolCallDelta-(3)]
	_ = x[EventKindUsage-(4)]
	_ = x[EventKindToolStart-(5)]
	_ = x[EventKindToolResult-(6)]
	_ = x[EventKindApprovalAsk-(7)]
	_ = x[EventKindApprovalReply-(8)]
	_ = x[EventKindTaskUpdate-(9)]
	_ = x[EventKindSessionTitle-(10)]
	_ = x[EventKindChatTitle-(11)]
	_ = x[EventKindError-(12)]
	_ = x[EventKindStatus-(13)]
}

var _EventKindValues = []EventKind{EventKindMessageDelta, EventKindMessageDone, EventKindReasoning, EventKindToolCallDelta, EventKindUsage, EventKindToolStart, EventKindToolResult, EventKindApprovalAsk, EventKindApprovalReply, EventKindTaskUpdate, EventKindSessionTitle, EventKindChatTitle, EventKindError, EventKindStatus}

var _EventKindNameToValueMap = map[string]EventKind{
	_EventKindName[0:13]:         EventKindMessageDelta,
	_EventKindLowerName[0:13]:    EventKindMessageDelta,
	_EventKindName[13:25]:        EventKindMessageDone,
	_EventKindLowerName[13:25]:   EventKindMessageDone,
	_EventKindName[25:34]:        EventKindReasoning,
	_EventKindLowerName[25:34]:   EventKindReasoning,
	_EventKindName[34:49]:        EventKindToolCallDelta,
	_EventKindLowerName[34:49]:   EventKindToolCallDelta,
	_EventKindName[49:54]:        EventKindUsage,
	_EventKindLowerName[49:54]:   EventKindUsage,
	_EventKindName[54:64]:        EventKindToolStart,
	_EventKindLowerName[54:64]:   EventKindToolStart,
	_EventKindName[64:75]:        EventKindToolResult,
	_EventKindLowerName[64:75]:   EventKindToolResult,
	_EventKindName[75:87]:        EventKindApprovalAsk,
	_EventKindLowerName[75:87]:   EventKindApprovalAsk,
	_EventKindName[87:101]:       EventKindApprovalReply,
	_EventKindLowerName[87:101]:  EventKindApprovalReply,
	_EventKindName[101:112]:      EventKindTaskUpdate,
	_EventKindLowerName[101:112]: EventKindTaskUpdate,
	_EventKindName[112:125]:      EventKindSessionTitle,
	_EventKindLowerName[112:125]: EventKindSessionTitle,
	_EventKindName[125:135]:      EventKindChatTitle,
	_EventKindLowerName[125:135]: EventKindChatTitle,
	_EventKindName[135:140]:      EventKindError,
	_EventKindLowerName[135:140]: EventKindError,
	_EventKindName[140:146]:      EventKindStatus,
	_EventKindLowerName[140:146]: EventKindStatus,
}

var _EventKindNames = []string{
	_EventKindName[0:13],
	_EventKindName[13:25],
	_EventKindName[25:34],
	_EventKindName[34:49],
	_EventKindName[49:54],
	_EventKindName[54:64],
	_EventKindName[64:75],
	_EventKindName[75:87],
	_EventKindName[87:101],
	_EventKindName[101:112],
	_EventKindName[112:125],
	_EventKindName[125:135],
	_EventKindName[135:140],
	_EventKindName[140:146],
}

// EventKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EventKindString(s string) (EventKind, error) {
	if val, ok := _EventKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EventKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EventKind values", s)
}

// EventKindValues returns all values of the enum
func EventKindValues() []EventKind {
	return _EventKindValues
}

// EventKindStrings returns a slice of all String values of the enum
func EventKindStrings() []string {
	strs := make([]string, len(_EventKindNames))
	copy(strs, _EventKindNames)
	return strs
}

// IsAEventKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EventKind) IsAEventKind() bool {
	for _, v := range _EventKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EventKind
func (i EventKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EventKind
func (i *EventKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EventKind should be a string, got %s", data)
	}

	var err error
	*i, err = EventKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for EventKind
func (i EventKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EventKind
func (i *EventKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = EventKindString(string(text))
	return err
}

const _QueuedInputKindName = "steerqueuedcontinuerejected_steer"

var _QueuedInputKindIndex = [...]uint8{0, 5, 11, 19, 33}

const _QueuedInputKindLowerName = "steerqueuedcontinuerejected_steer"

func (i QueuedInputKind) String() string {
	if i >= QueuedInputKind(len(_QueuedInputKindIndex)-1) {
		return fmt.Sprintf("QueuedInputKind(%d)", i)
	}
	return _QueuedInputKindName[_QueuedInputKindIndex[i]:_QueuedInputKindIndex[i+1]]
}

func (QueuedInputKind) Values() []string {
	return QueuedInputKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _QueuedInputKindNoOp() {
	var x [1]struct{}
	_ = x[QueuedInputKindSteer-(0)]
	_ = x[QueuedInputKindQueued-(1)]
	_ = x[QueuedInputKindContinue-(2)]
	_ = x[QueuedInputKindRejectedSteer-(3)]
}

var _QueuedInputKindValues = []QueuedInputKind{QueuedInputKindSteer, QueuedInputKindQueued, QueuedInputKindContinue, QueuedInputKindRejectedSteer}

var _QueuedInputKindNameToValueMap = map[string]QueuedInputKind{
	_QueuedInputKindName[0:5]:        QueuedInputKindSteer,
	_QueuedInputKindLowerName[0:5]:   QueuedInputKindSteer,
	_QueuedInputKindName[5:11]:       QueuedInputKindQueued,
	_QueuedInputKindLowerName[5:11]:  QueuedInputKindQueued,
	_QueuedInputKindName[11:19]:      QueuedInputKindContinue,
	_QueuedInputKindLowerName[11:19]: QueuedInputKindContinue,
	_QueuedInputKindName[19:33]:      QueuedInputKindRejectedSteer,
	_QueuedInputKindLowerName[19:33]: QueuedInputKindRejectedSteer,
}

var _QueuedInputKindNames = []string{
	_QueuedInputKindName[0:5],
	_QueuedInputKindName[5:11],
	_QueuedInputKindName[11:19],
	_QueuedInputKindName[19:33],
}

// QueuedInputKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func QueuedInputKindString(s string) (QueuedInputKind, error) {
	if val, ok := _QueuedInputKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _QueuedInputKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to QueuedInputKind values", s)
}

// QueuedInputKindValues returns all values of the enum
func QueuedInputKindValues() []QueuedInputKind {
	return _QueuedInputKindValues
}

// QueuedInputKindStrings returns a slice of all String values of the enum
func QueuedInputKindStrings() []string {
	strs := make([]string, len(_QueuedInputKindNames))
	copy(strs, _QueuedInputKindNames)
	return strs
}

// IsAQueuedInputKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i QueuedInputKind) IsAQueuedInputKind() bool {
	for _, v := range _QueuedInputKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for QueuedInputKind
func (i QueuedInputKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for QueuedInputKind
func (i *QueuedInputKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("QueuedInputKind should be a string, got %s", data)
	}

	var err error
	*i, err = QueuedInputKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for QueuedInputKind
func (i QueuedInputKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for QueuedInputKind
func (i *QueuedInputKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = QueuedInputKindString(string(text))
	return err
}
