// Code generated by "enumer -type=MessageRole,PartKind,ToolKind,PermissionMode,ApprovalStatus,TaskStatus,MilestoneStatus,TodoStatus,EventKind,QueuedInputKind -trimprefix=MessageRole,PartKind,ToolKind,PermissionMode,ApprovalStatus,TaskStatus,MilestoneStatus,TodoStatus,EventKind,QueuedInputKind -json -text -values -output=messagerole_enumer.go"; DO NOT EDIT.

package domain

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MessageRoleName = "SystemUserAssistantTool"

var _MessageRoleIndex = [...]uint8{0, 6, 10, 19, 23}

const _MessageRoleLowerName = "systemuserassistanttool"

func (i MessageRole) String() string {
	if i >= MessageRole(len(_MessageRoleIndex)-1) {
		return fmt.Sprintf("MessageRole(%d)", i)
	}
	return _MessageRoleName[_MessageRoleIndex[i]:_MessageRoleIndex[i+1]]
}

func (MessageRole) Values() []string {
	return MessageRoleStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MessageRoleNoOp() {
	var x [1]struct{}
	_ = x[MessageRoleSystem-(0)]
	_ = x[MessageRoleUser-(1)]
	_ = x[MessageRoleAssistant-(2)]
	_ = x[MessageRoleTool-(3)]
}

var _MessageRoleValues = []MessageRole{MessageRoleSystem, MessageRoleUser, MessageRoleAssistant, MessageRoleTool}

var _MessageRoleNameToValueMap = map[string]MessageRole{
	_MessageRoleName[0:6]:        MessageRoleSystem,
	_MessageRoleLowerName[0:6]:   MessageRoleSystem,
	_MessageRoleName[6:10]:       MessageRoleUser,
	_MessageRoleLowerName[6:10]:  MessageRoleUser,
	_MessageRoleName[10:19]:      MessageRoleAssistant,
	_MessageRoleLowerName[10:19]: MessageRoleAssistant,
	_MessageRoleName[19:23]:      MessageRoleTool,
	_MessageRoleLowerName[19:23]: MessageRoleTool,
}

var _MessageRoleNames = []string{
	_MessageRoleName[0:6],
	_MessageRoleName[6:10],
	_MessageRoleName[10:19],
	_MessageRoleName[19:23],
}

// MessageRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MessageRoleString(s string) (MessageRole, error) {
	if val, ok := _MessageRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MessageRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MessageRole values", s)
}

// MessageRoleValues returns all values of the enum
func MessageRoleValues() []MessageRole {
	return _MessageRoleValues
}

// MessageRoleStrings returns a slice of all String values of the enum
func MessageRoleStrings() []string {
	strs := make([]string, len(_MessageRoleNames))
	copy(strs, _MessageRoleNames)
	return strs
}

// IsAMessageRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MessageRole) IsAMessageRole() bool {
	for _, v := range _MessageRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MessageRole
func (i MessageRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MessageRole
func (i *MessageRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MessageRole should be a string, got %s", data)
	}

	var err error
	*i, err = MessageRoleString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for MessageRole
func (i MessageRole) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for MessageRole
func (i *MessageRole) UnmarshalText(text []byte) error {
	var err error
	*i, err = MessageRoleString(string(text))
	return err
}

const _PartKindName = "TextAttachmentReferenceReasoningToolCallToolOutputCompactionApprovalRequestQuestionTaskUpdatePlanUpdateUsageSystemNoticeEventNotice"

var _PartKindIndex = [...]uint8{0, 4, 14, 23, 32, 40, 50, 60, 75, 83, 93, 103, 108, 120, 131}

const _PartKindLowerName = "textattachmentreferencereasoningtoolcalltooloutputcompactionapprovalrequestquestiontaskupdateplanupdateusagesystemnoticeeventnotice"

func (i PartKind) String() string {
	if i >= PartKind(len(_PartKindIndex)-1) {
		return fmt.Sprintf("PartKind(%d)", i)
	}
	return _PartKindName[_PartKindIndex[i]:_PartKindIndex[i+1]]
}

func (PartKind) Values() []string {
	return PartKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PartKindNoOp() {
	var x [1]struct{}
	_ = x[PartKindText-(0)]
	_ = x[PartKindAttachment-(1)]
	_ = x[PartKindReference-(2)]
	_ = x[PartKindReasoning-(3)]
	_ = x[PartKindToolCall-(4)]
	_ = x[PartKindToolOutput-(5)]
	_ = x[PartKindCompaction-(6)]
	_ = x[PartKindApprovalRequest-(7)]
	_ = x[PartKindQuestion-(8)]
	_ = x[PartKindTaskUpdate-(9)]
	_ = x[PartKindPlanUpdate-(10)]
	_ = x[PartKindUsage-(11)]
	_ = x[PartKindSystemNotice-(12)]
	_ = x[PartKindEventNotice-(13)]
}

var _PartKindValues = []PartKind{PartKindText, PartKindAttachment, PartKindReference, PartKindReasoning, PartKindToolCall, PartKindToolOutput, PartKindCompaction, PartKindApprovalRequest, PartKindQuestion, PartKindTaskUpdate, PartKindPlanUpdate, PartKindUsage, PartKindSystemNotice, PartKindEventNotice}

var _PartKindNameToValueMap = map[string]PartKind{
	_PartKindName[0:4]:          PartKindText,
	_PartKindLowerName[0:4]:     PartKindText,
	_PartKindName[4:14]:         PartKindAttachment,
	_PartKindLowerName[4:14]:    PartKindAttachment,
	_PartKindName[14:23]:        PartKindReference,
	_PartKindLowerName[14:23]:   PartKindReference,
	_PartKindName[23:32]:        PartKindReasoning,
	_PartKindLowerName[23:32]:   PartKindReasoning,
	_PartKindName[32:40]:        PartKindToolCall,
	_PartKindLowerName[32:40]:   PartKindToolCall,
	_PartKindName[40:50]:        PartKindToolOutput,
	_PartKindLowerName[40:50]:   PartKindToolOutput,
	_PartKindName[50:60]:        PartKindCompaction,
	_PartKindLowerName[50:60]:   PartKindCompaction,
	_PartKindName[60:75]:        PartKindApprovalRequest,
	_PartKindLowerName[60:75]:   PartKindApprovalRequest,
	_PartKindName[75:83]:        PartKindQuestion,
	_PartKindLowerName[75:83]:   PartKindQuestion,
	_PartKindName[83:93]:        PartKindTaskUpdate,
	_PartKindLowerName[83:93]:   PartKindTaskUpdate,
	_PartKindName[93:103]:       PartKindPlanUpdate,
	_PartKindLowerName[93:103]:  PartKindPlanUpdate,
	_PartKindName[103:108]:      PartKindUsage,
	_PartKindLowerName[103:108]: PartKindUsage,
	_PartKindName[108:120]:      PartKindSystemNotice,
	_PartKindLowerName[108:120]: PartKindSystemNotice,
	_PartKindName[120:131]:      PartKindEventNotice,
	_PartKindLowerName[120:131]: PartKindEventNotice,
}

var _PartKindNames = []string{
	_PartKindName[0:4],
	_PartKindName[4:14],
	_PartKindName[14:23],
	_PartKindName[23:32],
	_PartKindName[32:40],
	_PartKindName[40:50],
	_PartKindName[50:60],
	_PartKindName[60:75],
	_PartKindName[75:83],
	_PartKindName[83:93],
	_PartKindName[93:103],
	_PartKindName[103:108],
	_PartKindName[108:120],
	_PartKindName[120:131],
}

// PartKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PartKindString(s string) (PartKind, error) {
	if val, ok := _PartKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PartKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PartKind values", s)
}

// PartKindValues returns all values of the enum
func PartKindValues() []PartKind {
	return _PartKindValues
}

// PartKindStrings returns a slice of all String values of the enum
func PartKindStrings() []string {
	strs := make([]string, len(_PartKindNames))
	copy(strs, _PartKindNames)
	return strs
}

// IsAPartKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PartKind) IsAPartKind() bool {
	for _, v := range _PartKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PartKind
func (i PartKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PartKind
func (i *PartKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PartKind should be a string, got %s", data)
	}

	var err error
	*i, err = PartKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for PartKind
func (i PartKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PartKind
func (i *PartKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = PartKindString(string(text))
	return err
}

const _ToolKindName = "ReadViewImageShowImageGlobGrepCodeSearchLintBashExecCommandExecStatusExecListExecWriteStdinExecResizeExecTerminateExecCleanupEditWriteTaskQuestionUpdatePlanMilestoneListMilestoneAddMilestoneUpdateMilestonePlanMilestoneWriteTodoListTodoAddItemsTodoUpdateItemTodoFetchNextChatListChatStartChatPollChatArchiveSkillWebFetchWebSearchMCPApplyPatchChatStartDecompositionChatStartExecution"

var _ToolKindIndex = [...]uint16{0, 4, 13, 22, 26, 30, 40, 44, 48, 59, 69, 77, 91, 101, 114, 125, 129, 134, 138, 146, 156, 169, 181, 196, 209, 223, 231, 243, 257, 270, 278, 287, 295, 306, 311, 319, 328, 331, 341, 363, 381}

const _ToolKindLowerName = "readviewimageshowimageglobgrepcodesearchlintbashexeccommandexecstatusexeclistexecwritestdinexecresizeexecterminateexeccleanupeditwritetaskquestionupdateplanmilestonelistmilestoneaddmilestoneupdatemilestoneplanmilestonewritetodolisttodoadditemstodoupdateitemtodofetchnextchatlistchatstartchatpollchatarchiveskillwebfetchwebsearchmcpapplypatchchatstartdecompositionchatstartexecution"

func (i ToolKind) String() string {
	i -= 1
	if i >= ToolKind(len(_ToolKindIndex)-1) {
		return fmt.Sprintf("ToolKind(%d)", i+1)
	}
	return _ToolKindName[_ToolKindIndex[i]:_ToolKindIndex[i+1]]
}

func (ToolKind) Values() []string {
	return ToolKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ToolKindNoOp() {
	var x [1]struct{}
	_ = x[ToolKindRead-(1)]
	_ = x[ToolKindViewImage-(2)]
	_ = x[ToolKindShowImage-(3)]
	_ = x[ToolKindGlob-(4)]
	_ = x[ToolKindGrep-(5)]
	_ = x[ToolKindCodeSearch-(6)]
	_ = x[ToolKindLint-(7)]
	_ = x[ToolKindBash-(8)]
	_ = x[ToolKindExecCommand-(9)]
	_ = x[ToolKindExecStatus-(10)]
	_ = x[ToolKindExecList-(11)]
	_ = x[ToolKindExecWriteStdin-(12)]
	_ = x[ToolKindExecResize-(13)]
	_ = x[ToolKindExecTerminate-(14)]
	_ = x[ToolKindExecCleanup-(15)]
	_ = x[ToolKindEdit-(16)]
	_ = x[ToolKindWrite-(17)]
	_ = x[ToolKindTask-(18)]
	_ = x[ToolKindQuestion-(19)]
	_ = x[ToolKindUpdatePlan-(20)]
	_ = x[ToolKindMilestoneList-(21)]
	_ = x[ToolKindMilestoneAdd-(22)]
	_ = x[ToolKindMilestoneUpdate-(23)]
	_ = x[ToolKindMilestonePlan-(24)]
	_ = x[ToolKindMilestoneWrite-(25)]
	_ = x[ToolKindTodoList-(26)]
	_ = x[ToolKindTodoAddItems-(27)]
	_ = x[ToolKindTodoUpdateItem-(28)]
	_ = x[ToolKindTodoFetchNext-(29)]
	_ = x[ToolKindChatList-(30)]
	_ = x[ToolKindChatStart-(31)]
	_ = x[ToolKindChatPoll-(32)]
	_ = x[ToolKindChatArchive-(33)]
	_ = x[ToolKindSkill-(34)]
	_ = x[ToolKindWebFetch-(35)]
	_ = x[ToolKindWebSearch-(36)]
	_ = x[ToolKindMCP-(37)]
	_ = x[ToolKindApplyPatch-(38)]
	_ = x[ToolKindChatStartDecomposition-(39)]
	_ = x[ToolKindChatStartExecution-(40)]
}

var _ToolKindValues = []ToolKind{ToolKindRead, ToolKindViewImage, ToolKindShowImage, ToolKindGlob, ToolKindGrep, ToolKindCodeSearch, ToolKindLint, ToolKindBash, ToolKindExecCommand, ToolKindExecStatus, ToolKindExecList, ToolKindExecWriteStdin, ToolKindExecResize, ToolKindExecTerminate, ToolKindExecCleanup, ToolKindEdit, ToolKindWrite, ToolKindTask, ToolKindQuestion, ToolKindUpdatePlan, ToolKindMilestoneList, ToolKindMilestoneAdd, ToolKindMilestoneUpdate, ToolKindMilestonePlan, ToolKindMilestoneWrite, ToolKindTodoList, ToolKindTodoAddItems, ToolKindTodoUpdateItem, ToolKindTodoFetchNext, ToolKindChatList, ToolKindChatStart, ToolKindChatPoll, ToolKindChatArchive, ToolKindSkill, ToolKindWebFetch, ToolKindWebSearch, ToolKindMCP, ToolKindApplyPatch, ToolKindChatStartDecomposition, ToolKindChatStartExecution}

var _ToolKindNameToValueMap = map[string]ToolKind{
	_ToolKindName[0:4]:          ToolKindRead,
	_ToolKindLowerName[0:4]:     ToolKindRead,
	_ToolKindName[4:13]:         ToolKindViewImage,
	_ToolKindLowerName[4:13]:    ToolKindViewImage,
	_ToolKindName[13:22]:        ToolKindShowImage,
	_ToolKindLowerName[13:22]:   ToolKindShowImage,
	_ToolKindName[22:26]:        ToolKindGlob,
	_ToolKindLowerName[22:26]:   ToolKindGlob,
	_ToolKindName[26:30]:        ToolKindGrep,
	_ToolKindLowerName[26:30]:   ToolKindGrep,
	_ToolKindName[30:40]:        ToolKindCodeSearch,
	_ToolKindLowerName[30:40]:   ToolKindCodeSearch,
	_ToolKindName[40:44]:        ToolKindLint,
	_ToolKindLowerName[40:44]:   ToolKindLint,
	_ToolKindName[44:48]:        ToolKindBash,
	_ToolKindLowerName[44:48]:   ToolKindBash,
	_ToolKindName[48:59]:        ToolKindExecCommand,
	_ToolKindLowerName[48:59]:   ToolKindExecCommand,
	_ToolKindName[59:69]:        ToolKindExecStatus,
	_ToolKindLowerName[59:69]:   ToolKindExecStatus,
	_ToolKindName[69:77]:        ToolKindExecList,
	_ToolKindLowerName[69:77]:   ToolKindExecList,
	_ToolKindName[77:91]:        ToolKindExecWriteStdin,
	_ToolKindLowerName[77:91]:   ToolKindExecWriteStdin,
	_ToolKindName[91:101]:       ToolKindExecResize,
	_ToolKindLowerName[91:101]:  ToolKindExecResize,
	_ToolKindName[101:114]:      ToolKindExecTerminate,
	_ToolKindLowerName[101:114]: ToolKindExecTerminate,
	_ToolKindName[114:125]:      ToolKindExecCleanup,
	_ToolKindLowerName[114:125]: ToolKindExecCleanup,
	_ToolKindName[125:129]:      ToolKindEdit,
	_ToolKindLowerName[125:129]: ToolKindEdit,
	_ToolKindName[129:134]:      ToolKindWrite,
	_ToolKindLowerName[129:134]: ToolKindWrite,
	_ToolKindName[134:138]:      ToolKindTask,
	_ToolKindLowerName[134:138]: ToolKindTask,
	_ToolKindName[138:146]:      ToolKindQuestion,
	_ToolKindLowerName[138:146]: ToolKindQuestion,
	_ToolKindName[146:156]:      ToolKindUpdatePlan,
	_ToolKindLowerName[146:156]: ToolKindUpdatePlan,
	_ToolKindName[156:169]:      ToolKindMilestoneList,
	_ToolKindLowerName[156:169]: ToolKindMilestoneList,
	_ToolKindName[169:181]:      ToolKindMilestoneAdd,
	_ToolKindLowerName[169:181]: ToolKindMilestoneAdd,
	_ToolKindName[181:196]:      ToolKindMilestoneUpdate,
	_ToolKindLowerName[181:196]: ToolKindMilestoneUpdate,
	_ToolKindName[196:209]:      ToolKindMilestonePlan,
	_ToolKindLowerName[196:209]: ToolKindMilestonePlan,
	_ToolKindName[209:223]:      ToolKindMilestoneWrite,
	_ToolKindLowerName[209:223]: ToolKindMilestoneWrite,
	_ToolKindName[223:231]:      ToolKindTodoList,
	_ToolKindLowerName[223:231]: ToolKindTodoList,
	_ToolKindName[231:243]:      ToolKindTodoAddItems,
	_ToolKindLowerName[231:243]: ToolKindTodoAddItems,
	_ToolKindName[243:257]:      ToolKindTodoUpdateItem,
	_ToolKindLowerName[243:257]: ToolKindTodoUpdateItem,
	_ToolKindName[257:270]:      ToolKindTodoFetchNext,
	_ToolKindLowerName[257:270]: ToolKindTodoFetchNext,
	_ToolKindName[270:278]:      ToolKindChatList,
	_ToolKindLowerName[270:278]: ToolKindChatList,
	_ToolKindName[278:287]:      ToolKindChatStart,
	_ToolKindLowerName[278:287]: ToolKindChatStart,
	_ToolKindName[287:295]:      ToolKindChatPoll,
	_ToolKindLowerName[287:295]: ToolKindChatPoll,
	_ToolKindName[295:306]:      ToolKindChatArchive,
	_ToolKindLowerName[295:306]: ToolKindChatArchive,
	_ToolKindName[306:311]:      ToolKindSkill,
	_ToolKindLowerName[306:311]: ToolKindSkill,
	_ToolKindName[311:319]:      ToolKindWebFetch,
	_ToolKindLowerName[311:319]: ToolKindWebFetch,
	_ToolKindName[319:328]:      ToolKindWebSearch,
	_ToolKindLowerName[319:328]: ToolKindWebSearch,
	_ToolKindName[328:331]:      ToolKindMCP,
	_ToolKindLowerName[328:331]: ToolKindMCP,
	_ToolKindName[331:341]:      ToolKindApplyPatch,
	_ToolKindLowerName[331:341]: ToolKindApplyPatch,
	_ToolKindName[341:363]:      ToolKindChatStartDecomposition,
	_ToolKindLowerName[341:363]: ToolKindChatStartDecomposition,
	_ToolKindName[363:381]:      ToolKindChatStartExecution,
	_ToolKindLowerName[363:381]: ToolKindChatStartExecution,
}

var _ToolKindNames = []string{
	_ToolKindName[0:4],
	_ToolKindName[4:13],
	_ToolKindName[13:22],
	_ToolKindName[22:26],
	_ToolKindName[26:30],
	_ToolKindName[30:40],
	_ToolKindName[40:44],
	_ToolKindName[44:48],
	_ToolKindName[48:59],
	_ToolKindName[59:69],
	_ToolKindName[69:77],
	_ToolKindName[77:91],
	_ToolKindName[91:101],
	_ToolKindName[101:114],
	_ToolKindName[114:125],
	_ToolKindName[125:129],
	_ToolKindName[129:134],
	_ToolKindName[134:138],
	_ToolKindName[138:146],
	_ToolKindName[146:156],
	_ToolKindName[156:169],
	_ToolKindName[169:181],
	_ToolKindName[181:196],
	_ToolKindName[196:209],
	_ToolKindName[209:223],
	_ToolKindName[223:231],
	_ToolKindName[231:243],
	_ToolKindName[243:257],
	_ToolKindName[257:270],
	_ToolKindName[270:278],
	_ToolKindName[278:287],
	_ToolKindName[287:295],
	_ToolKindName[295:306],
	_ToolKindName[306:311],
	_ToolKindName[311:319],
	_ToolKindName[319:328],
	_ToolKindName[328:331],
	_ToolKindName[331:341],
	_ToolKindName[341:363],
	_ToolKindName[363:381],
}

// ToolKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ToolKindString(s string) (ToolKind, error) {
	if val, ok := _ToolKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ToolKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ToolKind values", s)
}

// ToolKindValues returns all values of the enum
func ToolKindValues() []ToolKind {
	return _ToolKindValues
}

// ToolKindStrings returns a slice of all String values of the enum
func ToolKindStrings() []string {
	strs := make([]string, len(_ToolKindNames))
	copy(strs, _ToolKindNames)
	return strs
}

// IsAToolKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ToolKind) IsAToolKind() bool {
	for _, v := range _ToolKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ToolKind
func (i ToolKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ToolKind
func (i *ToolKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ToolKind should be a string, got %s", data)
	}

	var err error
	*i, err = ToolKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ToolKind
func (i ToolKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ToolKind
func (i *ToolKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = ToolKindString(string(text))
	return err
}

const _PermissionModeName = "AllowAskDeny"

var _PermissionModeIndex = [...]uint8{0, 5, 8, 12}

const _PermissionModeLowerName = "allowaskdeny"

func (i PermissionMode) String() string {
	if i >= PermissionMode(len(_PermissionModeIndex)-1) {
		return fmt.Sprintf("PermissionMode(%d)", i)
	}
	return _PermissionModeName[_PermissionModeIndex[i]:_PermissionModeIndex[i+1]]
}

func (PermissionMode) Values() []string {
	return PermissionModeStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PermissionModeNoOp() {
	var x [1]struct{}
	_ = x[PermissionModeAllow-(0)]
	_ = x[PermissionModeAsk-(1)]
	_ = x[PermissionModeDeny-(2)]
}

var _PermissionModeValues = []PermissionMode{PermissionModeAllow, PermissionModeAsk, PermissionModeDeny}

var _PermissionModeNameToValueMap = map[string]PermissionMode{
	_PermissionModeName[0:5]:       PermissionModeAllow,
	_PermissionModeLowerName[0:5]:  PermissionModeAllow,
	_PermissionModeName[5:8]:       PermissionModeAsk,
	_PermissionModeLowerName[5:8]:  PermissionModeAsk,
	_PermissionModeName[8:12]:      PermissionModeDeny,
	_PermissionModeLowerName[8:12]: PermissionModeDeny,
}

var _PermissionModeNames = []string{
	_PermissionModeName[0:5],
	_PermissionModeName[5:8],
	_PermissionModeName[8:12],
}

// PermissionModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PermissionModeString(s string) (PermissionMode, error) {
	if val, ok := _PermissionModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PermissionModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PermissionMode values", s)
}

// PermissionModeValues returns all values of the enum
func PermissionModeValues() []PermissionMode {
	return _PermissionModeValues
}

// PermissionModeStrings returns a slice of all String values of the enum
func PermissionModeStrings() []string {
	strs := make([]string, len(_PermissionModeNames))
	copy(strs, _PermissionModeNames)
	return strs
}

// IsAPermissionMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PermissionMode) IsAPermissionMode() bool {
	for _, v := range _PermissionModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PermissionMode
func (i PermissionMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PermissionMode
func (i *PermissionMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PermissionMode should be a string, got %s", data)
	}

	var err error
	*i, err = PermissionModeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for PermissionMode
func (i PermissionMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PermissionMode
func (i *PermissionMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = PermissionModeString(string(text))
	return err
}

const _ApprovalStatusName = "PendingApprovedDenied"

var _ApprovalStatusIndex = [...]uint8{0, 7, 15, 21}

const _ApprovalStatusLowerName = "pendingapproveddenied"

func (i ApprovalStatus) String() string {
	if i >= ApprovalStatus(len(_ApprovalStatusIndex)-1) {
		return fmt.Sprintf("ApprovalStatus(%d)", i)
	}
	return _ApprovalStatusName[_ApprovalStatusIndex[i]:_ApprovalStatusIndex[i+1]]
}

func (ApprovalStatus) Values() []string {
	return ApprovalStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ApprovalStatusNoOp() {
	var x [1]struct{}
	_ = x[ApprovalStatusPending-(0)]
	_ = x[ApprovalStatusApproved-(1)]
	_ = x[ApprovalStatusDenied-(2)]
}

var _ApprovalStatusValues = []ApprovalStatus{ApprovalStatusPending, ApprovalStatusApproved, ApprovalStatusDenied}

var _ApprovalStatusNameToValueMap = map[string]ApprovalStatus{
	_ApprovalStatusName[0:7]:        ApprovalStatusPending,
	_ApprovalStatusLowerName[0:7]:   ApprovalStatusPending,
	_ApprovalStatusName[7:15]:       ApprovalStatusApproved,
	_ApprovalStatusLowerName[7:15]:  ApprovalStatusApproved,
	_ApprovalStatusName[15:21]:      ApprovalStatusDenied,
	_ApprovalStatusLowerName[15:21]: ApprovalStatusDenied,
}

var _ApprovalStatusNames = []string{
	_ApprovalStatusName[0:7],
	_ApprovalStatusName[7:15],
	_ApprovalStatusName[15:21],
}

// ApprovalStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ApprovalStatusString(s string) (ApprovalStatus, error) {
	if val, ok := _ApprovalStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ApprovalStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ApprovalStatus values", s)
}

// ApprovalStatusValues returns all values of the enum
func ApprovalStatusValues() []ApprovalStatus {
	return _ApprovalStatusValues
}

// ApprovalStatusStrings returns a slice of all String values of the enum
func ApprovalStatusStrings() []string {
	strs := make([]string, len(_ApprovalStatusNames))
	copy(strs, _ApprovalStatusNames)
	return strs
}

// IsAApprovalStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ApprovalStatus) IsAApprovalStatus() bool {
	for _, v := range _ApprovalStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ApprovalStatus
func (i ApprovalStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ApprovalStatus
func (i *ApprovalStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ApprovalStatus should be a string, got %s", data)
	}

	var err error
	*i, err = ApprovalStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ApprovalStatus
func (i ApprovalStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ApprovalStatus
func (i *ApprovalStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = ApprovalStatusString(string(text))
	return err
}

const _TaskStatusName = "PendingInProgressCompletedCancelled"

var _TaskStatusIndex = [...]uint8{0, 7, 17, 26, 35}

const _TaskStatusLowerName = "pendinginprogresscompletedcancelled"

func (i TaskStatus) String() string {
	if i >= TaskStatus(len(_TaskStatusIndex)-1) {
		return fmt.Sprintf("TaskStatus(%d)", i)
	}
	return _TaskStatusName[_TaskStatusIndex[i]:_TaskStatusIndex[i+1]]
}

func (TaskStatus) Values() []string {
	return TaskStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TaskStatusNoOp() {
	var x [1]struct{}
	_ = x[TaskStatusPending-(0)]
	_ = x[TaskStatusInProgress-(1)]
	_ = x[TaskStatusCompleted-(2)]
	_ = x[TaskStatusCancelled-(3)]
}

var _TaskStatusValues = []TaskStatus{TaskStatusPending, TaskStatusInProgress, TaskStatusCompleted, TaskStatusCancelled}

var _TaskStatusNameToValueMap = map[string]TaskStatus{
	_TaskStatusName[0:7]:        TaskStatusPending,
	_TaskStatusLowerName[0:7]:   TaskStatusPending,
	_TaskStatusName[7:17]:       TaskStatusInProgress,
	_TaskStatusLowerName[7:17]:  TaskStatusInProgress,
	_TaskStatusName[17:26]:      TaskStatusCompleted,
	_TaskStatusLowerName[17:26]: TaskStatusCompleted,
	_TaskStatusName[26:35]:      TaskStatusCancelled,
	_TaskStatusLowerName[26:35]: TaskStatusCancelled,
}

var _TaskStatusNames = []string{
	_TaskStatusName[0:7],
	_TaskStatusName[7:17],
	_TaskStatusName[17:26],
	_TaskStatusName[26:35],
}

// TaskStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TaskStatusString(s string) (TaskStatus, error) {
	if val, ok := _TaskStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TaskStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TaskStatus values", s)
}

// TaskStatusValues returns all values of the enum
func TaskStatusValues() []TaskStatus {
	return _TaskStatusValues
}

// TaskStatusStrings returns a slice of all String values of the enum
func TaskStatusStrings() []string {
	strs := make([]string, len(_TaskStatusNames))
	copy(strs, _TaskStatusNames)
	return strs
}

// IsATaskStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TaskStatus) IsATaskStatus() bool {
	for _, v := range _TaskStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TaskStatus
func (i TaskStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TaskStatus
func (i *TaskStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TaskStatus should be a string, got %s", data)
	}

	var err error
	*i, err = TaskStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TaskStatus
func (i TaskStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TaskStatus
func (i *TaskStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = TaskStatusString(string(text))
	return err
}

const _MilestoneStatusName = "PendingDecomposingReadyExecutingCompletedBlockedCancelled"

var _MilestoneStatusIndex = [...]uint8{0, 7, 18, 23, 32, 41, 48, 57}

const _MilestoneStatusLowerName = "pendingdecomposingreadyexecutingcompletedblockedcancelled"

func (i MilestoneStatus) String() string {
	if i >= MilestoneStatus(len(_MilestoneStatusIndex)-1) {
		return fmt.Sprintf("MilestoneStatus(%d)", i)
	}
	return _MilestoneStatusName[_MilestoneStatusIndex[i]:_MilestoneStatusIndex[i+1]]
}

func (MilestoneStatus) Values() []string {
	return MilestoneStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MilestoneStatusNoOp() {
	var x [1]struct{}
	_ = x[MilestoneStatusPending-(0)]
	_ = x[MilestoneStatusDecomposing-(1)]
	_ = x[MilestoneStatusReady-(2)]
	_ = x[MilestoneStatusExecuting-(3)]
	_ = x[MilestoneStatusCompleted-(4)]
	_ = x[MilestoneStatusBlocked-(5)]
	_ = x[MilestoneStatusCancelled-(6)]
}

var _MilestoneStatusValues = []MilestoneStatus{MilestoneStatusPending, MilestoneStatusDecomposing, MilestoneStatusReady, MilestoneStatusExecuting, MilestoneStatusCompleted, MilestoneStatusBlocked, MilestoneStatusCancelled}

var _MilestoneStatusNameToValueMap = map[string]MilestoneStatus{
	_MilestoneStatusName[0:7]:        MilestoneStatusPending,
	_MilestoneStatusLowerName[0:7]:   MilestoneStatusPending,
	_MilestoneStatusName[7:18]:       MilestoneStatusDecomposing,
	_MilestoneStatusLowerName[7:18]:  MilestoneStatusDecomposing,
	_MilestoneStatusName[18:23]:      MilestoneStatusReady,
	_MilestoneStatusLowerName[18:23]: MilestoneStatusReady,
	_MilestoneStatusName[23:32]:      MilestoneStatusExecuting,
	_MilestoneStatusLowerName[23:32]: MilestoneStatusExecuting,
	_MilestoneStatusName[32:41]:      MilestoneStatusCompleted,
	_MilestoneStatusLowerName[32:41]: MilestoneStatusCompleted,
	_MilestoneStatusName[41:48]:      MilestoneStatusBlocked,
	_MilestoneStatusLowerName[41:48]: MilestoneStatusBlocked,
	_MilestoneStatusName[48:57]:      MilestoneStatusCancelled,
	_MilestoneStatusLowerName[48:57]: MilestoneStatusCancelled,
}

var _MilestoneStatusNames = []string{
	_MilestoneStatusName[0:7],
	_MilestoneStatusName[7:18],
	_MilestoneStatusName[18:23],
	_MilestoneStatusName[23:32],
	_MilestoneStatusName[32:41],
	_MilestoneStatusName[41:48],
	_MilestoneStatusName[48:57],
}

// MilestoneStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MilestoneStatusString(s string) (MilestoneStatus, error) {
	if val, ok := _MilestoneStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MilestoneStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MilestoneStatus values", s)
}

// MilestoneStatusValues returns all values of the enum
func MilestoneStatusValues() []MilestoneStatus {
	return _MilestoneStatusValues
}

// MilestoneStatusStrings returns a slice of all String values of the enum
func MilestoneStatusStrings() []string {
	strs := make([]string, len(_MilestoneStatusNames))
	copy(strs, _MilestoneStatusNames)
	return strs
}

// IsAMilestoneStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MilestoneStatus) IsAMilestoneStatus() bool {
	for _, v := range _MilestoneStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MilestoneStatus
func (i MilestoneStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MilestoneStatus
func (i *MilestoneStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MilestoneStatus should be a string, got %s", data)
	}

	var err error
	*i, err = MilestoneStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for MilestoneStatus
func (i MilestoneStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for MilestoneStatus
func (i *MilestoneStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = MilestoneStatusString(string(text))
	return err
}

const _TodoStatusName = "PendingInProgressCompleted"

var _TodoStatusIndex = [...]uint8{0, 7, 17, 26}

const _TodoStatusLowerName = "pendinginprogresscompleted"

func (i TodoStatus) String() string {
	if i >= TodoStatus(len(_TodoStatusIndex)-1) {
		return fmt.Sprintf("TodoStatus(%d)", i)
	}
	return _TodoStatusName[_TodoStatusIndex[i]:_TodoStatusIndex[i+1]]
}

func (TodoStatus) Values() []string {
	return TodoStatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TodoStatusNoOp() {
	var x [1]struct{}
	_ = x[TodoStatusPending-(0)]
	_ = x[TodoStatusInProgress-(1)]
	_ = x[TodoStatusCompleted-(2)]
}

var _TodoStatusValues = []TodoStatus{TodoStatusPending, TodoStatusInProgress, TodoStatusCompleted}

var _TodoStatusNameToValueMap = map[string]TodoStatus{
	_TodoStatusName[0:7]:        TodoStatusPending,
	_TodoStatusLowerName[0:7]:   TodoStatusPending,
	_TodoStatusName[7:17]:       TodoStatusInProgress,
	_TodoStatusLowerName[7:17]:  TodoStatusInProgress,
	_TodoStatusName[17:26]:      TodoStatusCompleted,
	_TodoStatusLowerName[17:26]: TodoStatusCompleted,
}

var _TodoStatusNames = []string{
	_TodoStatusName[0:7],
	_TodoStatusName[7:17],
	_TodoStatusName[17:26],
}

// TodoStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TodoStatusString(s string) (TodoStatus, error) {
	if val, ok := _TodoStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TodoStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TodoStatus values", s)
}

// TodoStatusValues returns all values of the enum
func TodoStatusValues() []TodoStatus {
	return _TodoStatusValues
}

// TodoStatusStrings returns a slice of all String values of the enum
func TodoStatusStrings() []string {
	strs := make([]string, len(_TodoStatusNames))
	copy(strs, _TodoStatusNames)
	return strs
}

// IsATodoStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TodoStatus) IsATodoStatus() bool {
	for _, v := range _TodoStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TodoStatus
func (i TodoStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TodoStatus
func (i *TodoStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TodoStatus should be a string, got %s", data)
	}

	var err error
	*i, err = TodoStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TodoStatus
func (i TodoStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TodoStatus
func (i *TodoStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = TodoStatusString(string(text))
	return err
}

const _EventKindName = "MessageDeltaMessageDoneReasoningToolCallDeltaUsageToolStartToolResultApprovalAskApprovalReplyTaskUpdateSessionTitleChatTitleErrorStatus"

var _EventKindIndex = [...]uint8{0, 12, 23, 32, 45, 50, 59, 69, 80, 93, 103, 115, 124, 129, 135}

const _EventKindLowerName = "messagedeltamessagedonereasoningtoolcalldeltausagetoolstarttoolresultapprovalaskapprovalreplytaskupdatesessiontitlechattitleerrorstatus"

func (i EventKind) String() string {
	if i >= EventKind(len(_EventKindIndex)-1) {
		return fmt.Sprintf("EventKind(%d)", i)
	}
	return _EventKindName[_EventKindIndex[i]:_EventKindIndex[i+1]]
}

func (EventKind) Values() []string {
	return EventKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EventKindNoOp() {
	var x [1]struct{}
	_ = x[EventKindMessageDelta-(0)]
	_ = x[EventKindMessageDone-(1)]
	_ = x[EventKindReasoning-(2)]
	_ = x[EventKindToolCallDelta-(3)]
	_ = x[EventKindUsage-(4)]
	_ = x[EventKindToolStart-(5)]
	_ = x[EventKindToolResult-(6)]
	_ = x[EventKindApprovalAsk-(7)]
	_ = x[EventKindApprovalReply-(8)]
	_ = x[EventKindTaskUpdate-(9)]
	_ = x[EventKindSessionTitle-(10)]
	_ = x[EventKindChatTitle-(11)]
	_ = x[EventKindError-(12)]
	_ = x[EventKindStatus-(13)]
}

var _EventKindValues = []EventKind{EventKindMessageDelta, EventKindMessageDone, EventKindReasoning, EventKindToolCallDelta, EventKindUsage, EventKindToolStart, EventKindToolResult, EventKindApprovalAsk, EventKindApprovalReply, EventKindTaskUpdate, EventKindSessionTitle, EventKindChatTitle, EventKindError, EventKindStatus}

var _EventKindNameToValueMap = map[string]EventKind{
	_EventKindName[0:12]:         EventKindMessageDelta,
	_EventKindLowerName[0:12]:    EventKindMessageDelta,
	_EventKindName[12:23]:        EventKindMessageDone,
	_EventKindLowerName[12:23]:   EventKindMessageDone,
	_EventKindName[23:32]:        EventKindReasoning,
	_EventKindLowerName[23:32]:   EventKindReasoning,
	_EventKindName[32:45]:        EventKindToolCallDelta,
	_EventKindLowerName[32:45]:   EventKindToolCallDelta,
	_EventKindName[45:50]:        EventKindUsage,
	_EventKindLowerName[45:50]:   EventKindUsage,
	_EventKindName[50:59]:        EventKindToolStart,
	_EventKindLowerName[50:59]:   EventKindToolStart,
	_EventKindName[59:69]:        EventKindToolResult,
	_EventKindLowerName[59:69]:   EventKindToolResult,
	_EventKindName[69:80]:        EventKindApprovalAsk,
	_EventKindLowerName[69:80]:   EventKindApprovalAsk,
	_EventKindName[80:93]:        EventKindApprovalReply,
	_EventKindLowerName[80:93]:   EventKindApprovalReply,
	_EventKindName[93:103]:       EventKindTaskUpdate,
	_EventKindLowerName[93:103]:  EventKindTaskUpdate,
	_EventKindName[103:115]:      EventKindSessionTitle,
	_EventKindLowerName[103:115]: EventKindSessionTitle,
	_EventKindName[115:124]:      EventKindChatTitle,
	_EventKindLowerName[115:124]: EventKindChatTitle,
	_EventKindName[124:129]:      EventKindError,
	_EventKindLowerName[124:129]: EventKindError,
	_EventKindName[129:135]:      EventKindStatus,
	_EventKindLowerName[129:135]: EventKindStatus,
}

var _EventKindNames = []string{
	_EventKindName[0:12],
	_EventKindName[12:23],
	_EventKindName[23:32],
	_EventKindName[32:45],
	_EventKindName[45:50],
	_EventKindName[50:59],
	_EventKindName[59:69],
	_EventKindName[69:80],
	_EventKindName[80:93],
	_EventKindName[93:103],
	_EventKindName[103:115],
	_EventKindName[115:124],
	_EventKindName[124:129],
	_EventKindName[129:135],
}

// EventKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EventKindString(s string) (EventKind, error) {
	if val, ok := _EventKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EventKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EventKind values", s)
}

// EventKindValues returns all values of the enum
func EventKindValues() []EventKind {
	return _EventKindValues
}

// EventKindStrings returns a slice of all String values of the enum
func EventKindStrings() []string {
	strs := make([]string, len(_EventKindNames))
	copy(strs, _EventKindNames)
	return strs
}

// IsAEventKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EventKind) IsAEventKind() bool {
	for _, v := range _EventKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EventKind
func (i EventKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EventKind
func (i *EventKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EventKind should be a string, got %s", data)
	}

	var err error
	*i, err = EventKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for EventKind
func (i EventKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EventKind
func (i *EventKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = EventKindString(string(text))
	return err
}

const _QueuedInputKindName = "SteerQueuedContinueRejectedSteer"

var _QueuedInputKindIndex = [...]uint8{0, 5, 11, 19, 32}

const _QueuedInputKindLowerName = "steerqueuedcontinuerejectedsteer"

func (i QueuedInputKind) String() string {
	if i >= QueuedInputKind(len(_QueuedInputKindIndex)-1) {
		return fmt.Sprintf("QueuedInputKind(%d)", i)
	}
	return _QueuedInputKindName[_QueuedInputKindIndex[i]:_QueuedInputKindIndex[i+1]]
}

func (QueuedInputKind) Values() []string {
	return QueuedInputKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _QueuedInputKindNoOp() {
	var x [1]struct{}
	_ = x[QueuedInputKindSteer-(0)]
	_ = x[QueuedInputKindQueued-(1)]
	_ = x[QueuedInputKindContinue-(2)]
	_ = x[QueuedInputKindRejectedSteer-(3)]
}

var _QueuedInputKindValues = []QueuedInputKind{QueuedInputKindSteer, QueuedInputKindQueued, QueuedInputKindContinue, QueuedInputKindRejectedSteer}

var _QueuedInputKindNameToValueMap = map[string]QueuedInputKind{
	_QueuedInputKindName[0:5]:        QueuedInputKindSteer,
	_QueuedInputKindLowerName[0:5]:   QueuedInputKindSteer,
	_QueuedInputKindName[5:11]:       QueuedInputKindQueued,
	_QueuedInputKindLowerName[5:11]:  QueuedInputKindQueued,
	_QueuedInputKindName[11:19]:      QueuedInputKindContinue,
	_QueuedInputKindLowerName[11:19]: QueuedInputKindContinue,
	_QueuedInputKindName[19:32]:      QueuedInputKindRejectedSteer,
	_QueuedInputKindLowerName[19:32]: QueuedInputKindRejectedSteer,
}

var _QueuedInputKindNames = []string{
	_QueuedInputKindName[0:5],
	_QueuedInputKindName[5:11],
	_QueuedInputKindName[11:19],
	_QueuedInputKindName[19:32],
}

// QueuedInputKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func QueuedInputKindString(s string) (QueuedInputKind, error) {
	if val, ok := _QueuedInputKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _QueuedInputKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to QueuedInputKind values", s)
}

// QueuedInputKindValues returns all values of the enum
func QueuedInputKindValues() []QueuedInputKind {
	return _QueuedInputKindValues
}

// QueuedInputKindStrings returns a slice of all String values of the enum
func QueuedInputKindStrings() []string {
	strs := make([]string, len(_QueuedInputKindNames))
	copy(strs, _QueuedInputKindNames)
	return strs
}

// IsAQueuedInputKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i QueuedInputKind) IsAQueuedInputKind() bool {
	for _, v := range _QueuedInputKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for QueuedInputKind
func (i QueuedInputKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for QueuedInputKind
func (i *QueuedInputKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("QueuedInputKind should be a string, got %s", data)
	}

	var err error
	*i, err = QueuedInputKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for QueuedInputKind
func (i QueuedInputKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for QueuedInputKind
func (i *QueuedInputKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = QueuedInputKindString(string(text))
	return err
}
