// Code generated by "enumer -type=ToolKind -trimprefix=ToolKind -transform=snake -json -text -values -output=toolkind_enumer.go"; DO NOT EDIT.

package domain

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ToolKindName = "readview_imageshow_imageglobgrepcode_searchlintbashexec_commandexec_statusexec_listexec_write_stdinexec_resizeexec_terminateexec_cleanupeditwritetaskquestionupdate_planmilestone_listmilestone_addmilestone_updatemilestone_planmilestone_writetodo_listtodo_add_itemstodo_update_itemtodo_fetch_nextchat_listchat_startchat_pollchat_archiveskillweb_fetchweb_searchmcpapply_patchchat_start_decompositionchat_start_execution"

var _ToolKindIndex = [...]uint16{0, 4, 14, 24, 28, 32, 43, 47, 51, 63, 74, 83, 99, 110, 124, 136, 140, 145, 149, 157, 168, 182, 195, 211, 225, 240, 249, 263, 279, 294, 303, 313, 322, 334, 339, 348, 358, 361, 372, 396, 416}

const _ToolKindLowerName = "readview_imageshow_imageglobgrepcode_searchlintbashexec_commandexec_statusexec_listexec_write_stdinexec_resizeexec_terminateexec_cleanupeditwritetaskquestionupdate_planmilestone_listmilestone_addmilestone_updatemilestone_planmilestone_writetodo_listtodo_add_itemstodo_update_itemtodo_fetch_nextchat_listchat_startchat_pollchat_archiveskillweb_fetchweb_searchmcpapply_patchchat_start_decompositionchat_start_execution"

func (i ToolKind) String() string {
	i -= 1
	if i >= ToolKind(len(_ToolKindIndex)-1) {
		return fmt.Sprintf("ToolKind(%d)", i+1)
	}
	return _ToolKindName[_ToolKindIndex[i]:_ToolKindIndex[i+1]]
}

func (ToolKind) Values() []string {
	return ToolKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ToolKindNoOp() {
	var x [1]struct{}
	_ = x[ToolKindRead-(1)]
	_ = x[ToolKindViewImage-(2)]
	_ = x[ToolKindShowImage-(3)]
	_ = x[ToolKindGlob-(4)]
	_ = x[ToolKindGrep-(5)]
	_ = x[ToolKindCodeSearch-(6)]
	_ = x[ToolKindLint-(7)]
	_ = x[ToolKindBash-(8)]
	_ = x[ToolKindExecCommand-(9)]
	_ = x[ToolKindExecStatus-(10)]
	_ = x[ToolKindExecList-(11)]
	_ = x[ToolKindExecWriteStdin-(12)]
	_ = x[ToolKindExecResize-(13)]
	_ = x[ToolKindExecTerminate-(14)]
	_ = x[ToolKindExecCleanup-(15)]
	_ = x[ToolKindEdit-(16)]
	_ = x[ToolKindWrite-(17)]
	_ = x[ToolKindTask-(18)]
	_ = x[ToolKindQuestion-(19)]
	_ = x[ToolKindUpdatePlan-(20)]
	_ = x[ToolKindMilestoneList-(21)]
	_ = x[ToolKindMilestoneAdd-(22)]
	_ = x[ToolKindMilestoneUpdate-(23)]
	_ = x[ToolKindMilestonePlan-(24)]
	_ = x[ToolKindMilestoneWrite-(25)]
	_ = x[ToolKindTodoList-(26)]
	_ = x[ToolKindTodoAddItems-(27)]
	_ = x[ToolKindTodoUpdateItem-(28)]
	_ = x[ToolKindTodoFetchNext-(29)]
	_ = x[ToolKindChatList-(30)]
	_ = x[ToolKindChatStart-(31)]
	_ = x[ToolKindChatPoll-(32)]
	_ = x[ToolKindChatArchive-(33)]
	_ = x[ToolKindSkill-(34)]
	_ = x[ToolKindWebFetch-(35)]
	_ = x[ToolKindWebSearch-(36)]
	_ = x[ToolKindMCP-(37)]
	_ = x[ToolKindApplyPatch-(38)]
	_ = x[ToolKindChatStartDecomposition-(39)]
	_ = x[ToolKindChatStartExecution-(40)]
}

var _ToolKindValues = []ToolKind{ToolKindRead, ToolKindViewImage, ToolKindShowImage, ToolKindGlob, ToolKindGrep, ToolKindCodeSearch, ToolKindLint, ToolKindBash, ToolKindExecCommand, ToolKindExecStatus, ToolKindExecList, ToolKindExecWriteStdin, ToolKindExecResize, ToolKindExecTerminate, ToolKindExecCleanup, ToolKindEdit, ToolKindWrite, ToolKindTask, ToolKindQuestion, ToolKindUpdatePlan, ToolKindMilestoneList, ToolKindMilestoneAdd, ToolKindMilestoneUpdate, ToolKindMilestonePlan, ToolKindMilestoneWrite, ToolKindTodoList, ToolKindTodoAddItems, ToolKindTodoUpdateItem, ToolKindTodoFetchNext, ToolKindChatList, ToolKindChatStart, ToolKindChatPoll, ToolKindChatArchive, ToolKindSkill, ToolKindWebFetch, ToolKindWebSearch, ToolKindMCP, ToolKindApplyPatch, ToolKindChatStartDecomposition, ToolKindChatStartExecution}

var _ToolKindNameToValueMap = map[string]ToolKind{
	_ToolKindName[0:4]:          ToolKindRead,
	_ToolKindLowerName[0:4]:     ToolKindRead,
	_ToolKindName[4:14]:         ToolKindViewImage,
	_ToolKindLowerName[4:14]:    ToolKindViewImage,
	_ToolKindName[14:24]:        ToolKindShowImage,
	_ToolKindLowerName[14:24]:   ToolKindShowImage,
	_ToolKindName[24:28]:        ToolKindGlob,
	_ToolKindLowerName[24:28]:   ToolKindGlob,
	_ToolKindName[28:32]:        ToolKindGrep,
	_ToolKindLowerName[28:32]:   ToolKindGrep,
	_ToolKindName[32:43]:        ToolKindCodeSearch,
	_ToolKindLowerName[32:43]:   ToolKindCodeSearch,
	_ToolKindName[43:47]:        ToolKindLint,
	_ToolKindLowerName[43:47]:   ToolKindLint,
	_ToolKindName[47:51]:        ToolKindBash,
	_ToolKindLowerName[47:51]:   ToolKindBash,
	_ToolKindName[51:63]:        ToolKindExecCommand,
	_ToolKindLowerName[51:63]:   ToolKindExecCommand,
	_ToolKindName[63:74]:        ToolKindExecStatus,
	_ToolKindLowerName[63:74]:   ToolKindExecStatus,
	_ToolKindName[74:83]:        ToolKindExecList,
	_ToolKindLowerName[74:83]:   ToolKindExecList,
	_ToolKindName[83:99]:        ToolKindExecWriteStdin,
	_ToolKindLowerName[83:99]:   ToolKindExecWriteStdin,
	_ToolKindName[99:110]:       ToolKindExecResize,
	_ToolKindLowerName[99:110]:  ToolKindExecResize,
	_ToolKindName[110:124]:      ToolKindExecTerminate,
	_ToolKindLowerName[110:124]: ToolKindExecTerminate,
	_ToolKindName[124:136]:      ToolKindExecCleanup,
	_ToolKindLowerName[124:136]: ToolKindExecCleanup,
	_ToolKindName[136:140]:      ToolKindEdit,
	_ToolKindLowerName[136:140]: ToolKindEdit,
	_ToolKindName[140:145]:      ToolKindWrite,
	_ToolKindLowerName[140:145]: ToolKindWrite,
	_ToolKindName[145:149]:      ToolKindTask,
	_ToolKindLowerName[145:149]: ToolKindTask,
	_ToolKindName[149:157]:      ToolKindQuestion,
	_ToolKindLowerName[149:157]: ToolKindQuestion,
	_ToolKindName[157:168]:      ToolKindUpdatePlan,
	_ToolKindLowerName[157:168]: ToolKindUpdatePlan,
	_ToolKindName[168:182]:      ToolKindMilestoneList,
	_ToolKindLowerName[168:182]: ToolKindMilestoneList,
	_ToolKindName[182:195]:      ToolKindMilestoneAdd,
	_ToolKindLowerName[182:195]: ToolKindMilestoneAdd,
	_ToolKindName[195:211]:      ToolKindMilestoneUpdate,
	_ToolKindLowerName[195:211]: ToolKindMilestoneUpdate,
	_ToolKindName[211:225]:      ToolKindMilestonePlan,
	_ToolKindLowerName[211:225]: ToolKindMilestonePlan,
	_ToolKindName[225:240]:      ToolKindMilestoneWrite,
	_ToolKindLowerName[225:240]: ToolKindMilestoneWrite,
	_ToolKindName[240:249]:      ToolKindTodoList,
	_ToolKindLowerName[240:249]: ToolKindTodoList,
	_ToolKindName[249:263]:      ToolKindTodoAddItems,
	_ToolKindLowerName[249:263]: ToolKindTodoAddItems,
	_ToolKindName[263:279]:      ToolKindTodoUpdateItem,
	_ToolKindLowerName[263:279]: ToolKindTodoUpdateItem,
	_ToolKindName[279:294]:      ToolKindTodoFetchNext,
	_ToolKindLowerName[279:294]: ToolKindTodoFetchNext,
	_ToolKindName[294:303]:      ToolKindChatList,
	_ToolKindLowerName[294:303]: ToolKindChatList,
	_ToolKindName[303:313]:      ToolKindChatStart,
	_ToolKindLowerName[303:313]: ToolKindChatStart,
	_ToolKindName[313:322]:      ToolKindChatPoll,
	_ToolKindLowerName[313:322]: ToolKindChatPoll,
	_ToolKindName[322:334]:      ToolKindChatArchive,
	_ToolKindLowerName[322:334]: ToolKindChatArchive,
	_ToolKindName[334:339]:      ToolKindSkill,
	_ToolKindLowerName[334:339]: ToolKindSkill,
	_ToolKindName[339:348]:      ToolKindWebFetch,
	_ToolKindLowerName[339:348]: ToolKindWebFetch,
	_ToolKindName[348:358]:      ToolKindWebSearch,
	_ToolKindLowerName[348:358]: ToolKindWebSearch,
	_ToolKindName[358:361]:      ToolKindMCP,
	_ToolKindLowerName[358:361]: ToolKindMCP,
	_ToolKindName[361:372]:      ToolKindApplyPatch,
	_ToolKindLowerName[361:372]: ToolKindApplyPatch,
	_ToolKindName[372:396]:      ToolKindChatStartDecomposition,
	_ToolKindLowerName[372:396]: ToolKindChatStartDecomposition,
	_ToolKindName[396:416]:      ToolKindChatStartExecution,
	_ToolKindLowerName[396:416]: ToolKindChatStartExecution,
}

var _ToolKindNames = []string{
	_ToolKindName[0:4],
	_ToolKindName[4:14],
	_ToolKindName[14:24],
	_ToolKindName[24:28],
	_ToolKindName[28:32],
	_ToolKindName[32:43],
	_ToolKindName[43:47],
	_ToolKindName[47:51],
	_ToolKindName[51:63],
	_ToolKindName[63:74],
	_ToolKindName[74:83],
	_ToolKindName[83:99],
	_ToolKindName[99:110],
	_ToolKindName[110:124],
	_ToolKindName[124:136],
	_ToolKindName[136:140],
	_ToolKindName[140:145],
	_ToolKindName[145:149],
	_ToolKindName[149:157],
	_ToolKindName[157:168],
	_ToolKindName[168:182],
	_ToolKindName[182:195],
	_ToolKindName[195:211],
	_ToolKindName[211:225],
	_ToolKindName[225:240],
	_ToolKindName[240:249],
	_ToolKindName[249:263],
	_ToolKindName[263:279],
	_ToolKindName[279:294],
	_ToolKindName[294:303],
	_ToolKindName[303:313],
	_ToolKindName[313:322],
	_ToolKindName[322:334],
	_ToolKindName[334:339],
	_ToolKindName[339:348],
	_ToolKindName[348:358],
	_ToolKindName[358:361],
	_ToolKindName[361:372],
	_ToolKindName[372:396],
	_ToolKindName[396:416],
}

// ToolKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ToolKindString(s string) (ToolKind, error) {
	if val, ok := _ToolKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ToolKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ToolKind values", s)
}

// ToolKindValues returns all values of the enum
func ToolKindValues() []ToolKind {
	return _ToolKindValues
}

// ToolKindStrings returns a slice of all String values of the enum
func ToolKindStrings() []string {
	strs := make([]string, len(_ToolKindNames))
	copy(strs, _ToolKindNames)
	return strs
}

// IsAToolKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ToolKind) IsAToolKind() bool {
	for _, v := range _ToolKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ToolKind
func (i ToolKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ToolKind
func (i *ToolKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ToolKind should be a string, got %s", data)
	}

	var err error
	*i, err = ToolKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ToolKind
func (i ToolKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ToolKind
func (i *ToolKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = ToolKindString(string(text))
	return err
}
