// Code generated by "enumer -type=ToolKind -trimprefix=ToolKind -transform=snake -json -text -values -output=toolkind_enumer.go"; DO NOT EDIT.

package domain

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ToolKindName = "file_readview_imageshow_imagefile_globfile_grepcode_searchlintbashexec_commandexec_statusexec_listexec_write_stdinexec_resizeexec_terminateexec_cleanupfile_editfile_writetaskquestionupdate_planmilestone_listmilestone_addmilestone_updatemilestone_planmilestone_writetodo_listtodo_add_itemstodo_update_itemtodo_fetch_nextchat_listchat_startchat_pollchat_archiveskillweb_fetchweb_searchmcpchat_start_decompositionchat_start_execution"

var _ToolKindIndex = [...]uint16{0, 9, 19, 29, 38, 47, 58, 62, 66, 78, 89, 98, 114, 125, 139, 151, 160, 170, 174, 182, 193, 207, 220, 236, 250, 265, 274, 288, 304, 319, 328, 338, 347, 359, 364, 373, 383, 386, 410, 430}

const _ToolKindLowerName = "file_readview_imageshow_imagefile_globfile_grepcode_searchlintbashexec_commandexec_statusexec_listexec_write_stdinexec_resizeexec_terminateexec_cleanupfile_editfile_writetaskquestionupdate_planmilestone_listmilestone_addmilestone_updatemilestone_planmilestone_writetodo_listtodo_add_itemstodo_update_itemtodo_fetch_nextchat_listchat_startchat_pollchat_archiveskillweb_fetchweb_searchmcpchat_start_decompositionchat_start_execution"

func (i ToolKind) String() string {
	i -= 1
	if i >= ToolKind(len(_ToolKindIndex)-1) {
		return fmt.Sprintf("ToolKind(%d)", i+1)
	}
	return _ToolKindName[_ToolKindIndex[i]:_ToolKindIndex[i+1]]
}

func (ToolKind) Values() []string {
	return ToolKindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ToolKindNoOp() {
	var x [1]struct{}
	_ = x[ToolKindFileRead-(1)]
	_ = x[ToolKindViewImage-(2)]
	_ = x[ToolKindShowImage-(3)]
	_ = x[ToolKindFileGlob-(4)]
	_ = x[ToolKindFileGrep-(5)]
	_ = x[ToolKindCodeSearch-(6)]
	_ = x[ToolKindLint-(7)]
	_ = x[ToolKindBash-(8)]
	_ = x[ToolKindExecCommand-(9)]
	_ = x[ToolKindExecStatus-(10)]
	_ = x[ToolKindExecList-(11)]
	_ = x[ToolKindExecWriteStdin-(12)]
	_ = x[ToolKindExecResize-(13)]
	_ = x[ToolKindExecTerminate-(14)]
	_ = x[ToolKindExecCleanup-(15)]
	_ = x[ToolKindFileEdit-(16)]
	_ = x[ToolKindFileWrite-(17)]
	_ = x[ToolKindTask-(18)]
	_ = x[ToolKindQuestion-(19)]
	_ = x[ToolKindUpdatePlan-(20)]
	_ = x[ToolKindMilestoneList-(21)]
	_ = x[ToolKindMilestoneAdd-(22)]
	_ = x[ToolKindMilestoneUpdate-(23)]
	_ = x[ToolKindMilestonePlan-(24)]
	_ = x[ToolKindMilestoneWrite-(25)]
	_ = x[ToolKindTodoList-(26)]
	_ = x[ToolKindTodoAddItems-(27)]
	_ = x[ToolKindTodoUpdateItem-(28)]
	_ = x[ToolKindTodoFetchNext-(29)]
	_ = x[ToolKindChatList-(30)]
	_ = x[ToolKindChatStart-(31)]
	_ = x[ToolKindChatPoll-(32)]
	_ = x[ToolKindChatArchive-(33)]
	_ = x[ToolKindSkill-(34)]
	_ = x[ToolKindWebFetch-(35)]
	_ = x[ToolKindWebSearch-(36)]
	_ = x[ToolKindMCP-(37)]
	_ = x[ToolKindChatStartDecomposition-(38)]
	_ = x[ToolKindChatStartExecution-(39)]
}

var _ToolKindValues = []ToolKind{ToolKindFileRead, ToolKindViewImage, ToolKindShowImage, ToolKindFileGlob, ToolKindFileGrep, ToolKindCodeSearch, ToolKindLint, ToolKindBash, ToolKindExecCommand, ToolKindExecStatus, ToolKindExecList, ToolKindExecWriteStdin, ToolKindExecResize, ToolKindExecTerminate, ToolKindExecCleanup, ToolKindFileEdit, ToolKindFileWrite, ToolKindTask, ToolKindQuestion, ToolKindUpdatePlan, ToolKindMilestoneList, ToolKindMilestoneAdd, ToolKindMilestoneUpdate, ToolKindMilestonePlan, ToolKindMilestoneWrite, ToolKindTodoList, ToolKindTodoAddItems, ToolKindTodoUpdateItem, ToolKindTodoFetchNext, ToolKindChatList, ToolKindChatStart, ToolKindChatPoll, ToolKindChatArchive, ToolKindSkill, ToolKindWebFetch, ToolKindWebSearch, ToolKindMCP, ToolKindChatStartDecomposition, ToolKindChatStartExecution}

var _ToolKindNameToValueMap = map[string]ToolKind{
	_ToolKindName[0:9]:          ToolKindFileRead,
	_ToolKindLowerName[0:9]:     ToolKindFileRead,
	_ToolKindName[9:19]:         ToolKindViewImage,
	_ToolKindLowerName[9:19]:    ToolKindViewImage,
	_ToolKindName[19:29]:        ToolKindShowImage,
	_ToolKindLowerName[19:29]:   ToolKindShowImage,
	_ToolKindName[29:38]:        ToolKindFileGlob,
	_ToolKindLowerName[29:38]:   ToolKindFileGlob,
	_ToolKindName[38:47]:        ToolKindFileGrep,
	_ToolKindLowerName[38:47]:   ToolKindFileGrep,
	_ToolKindName[47:58]:        ToolKindCodeSearch,
	_ToolKindLowerName[47:58]:   ToolKindCodeSearch,
	_ToolKindName[58:62]:        ToolKindLint,
	_ToolKindLowerName[58:62]:   ToolKindLint,
	_ToolKindName[62:66]:        ToolKindBash,
	_ToolKindLowerName[62:66]:   ToolKindBash,
	_ToolKindName[66:78]:        ToolKindExecCommand,
	_ToolKindLowerName[66:78]:   ToolKindExecCommand,
	_ToolKindName[78:89]:        ToolKindExecStatus,
	_ToolKindLowerName[78:89]:   ToolKindExecStatus,
	_ToolKindName[89:98]:        ToolKindExecList,
	_ToolKindLowerName[89:98]:   ToolKindExecList,
	_ToolKindName[98:114]:       ToolKindExecWriteStdin,
	_ToolKindLowerName[98:114]:  ToolKindExecWriteStdin,
	_ToolKindName[114:125]:      ToolKindExecResize,
	_ToolKindLowerName[114:125]: ToolKindExecResize,
	_ToolKindName[125:139]:      ToolKindExecTerminate,
	_ToolKindLowerName[125:139]: ToolKindExecTerminate,
	_ToolKindName[139:151]:      ToolKindExecCleanup,
	_ToolKindLowerName[139:151]: ToolKindExecCleanup,
	_ToolKindName[151:160]:      ToolKindFileEdit,
	_ToolKindLowerName[151:160]: ToolKindFileEdit,
	_ToolKindName[160:170]:      ToolKindFileWrite,
	_ToolKindLowerName[160:170]: ToolKindFileWrite,
	_ToolKindName[170:174]:      ToolKindTask,
	_ToolKindLowerName[170:174]: ToolKindTask,
	_ToolKindName[174:182]:      ToolKindQuestion,
	_ToolKindLowerName[174:182]: ToolKindQuestion,
	_ToolKindName[182:193]:      ToolKindUpdatePlan,
	_ToolKindLowerName[182:193]: ToolKindUpdatePlan,
	_ToolKindName[193:207]:      ToolKindMilestoneList,
	_ToolKindLowerName[193:207]: ToolKindMilestoneList,
	_ToolKindName[207:220]:      ToolKindMilestoneAdd,
	_ToolKindLowerName[207:220]: ToolKindMilestoneAdd,
	_ToolKindName[220:236]:      ToolKindMilestoneUpdate,
	_ToolKindLowerName[220:236]: ToolKindMilestoneUpdate,
	_ToolKindName[236:250]:      ToolKindMilestonePlan,
	_ToolKindLowerName[236:250]: ToolKindMilestonePlan,
	_ToolKindName[250:265]:      ToolKindMilestoneWrite,
	_ToolKindLowerName[250:265]: ToolKindMilestoneWrite,
	_ToolKindName[265:274]:      ToolKindTodoList,
	_ToolKindLowerName[265:274]: ToolKindTodoList,
	_ToolKindName[274:288]:      ToolKindTodoAddItems,
	_ToolKindLowerName[274:288]: ToolKindTodoAddItems,
	_ToolKindName[288:304]:      ToolKindTodoUpdateItem,
	_ToolKindLowerName[288:304]: ToolKindTodoUpdateItem,
	_ToolKindName[304:319]:      ToolKindTodoFetchNext,
	_ToolKindLowerName[304:319]: ToolKindTodoFetchNext,
	_ToolKindName[319:328]:      ToolKindChatList,
	_ToolKindLowerName[319:328]: ToolKindChatList,
	_ToolKindName[328:338]:      ToolKindChatStart,
	_ToolKindLowerName[328:338]: ToolKindChatStart,
	_ToolKindName[338:347]:      ToolKindChatPoll,
	_ToolKindLowerName[338:347]: ToolKindChatPoll,
	_ToolKindName[347:359]:      ToolKindChatArchive,
	_ToolKindLowerName[347:359]: ToolKindChatArchive,
	_ToolKindName[359:364]:      ToolKindSkill,
	_ToolKindLowerName[359:364]: ToolKindSkill,
	_ToolKindName[364:373]:      ToolKindWebFetch,
	_ToolKindLowerName[364:373]: ToolKindWebFetch,
	_ToolKindName[373:383]:      ToolKindWebSearch,
	_ToolKindLowerName[373:383]: ToolKindWebSearch,
	_ToolKindName[383:386]:      ToolKindMCP,
	_ToolKindLowerName[383:386]: ToolKindMCP,
	_ToolKindName[386:410]:      ToolKindChatStartDecomposition,
	_ToolKindLowerName[386:410]: ToolKindChatStartDecomposition,
	_ToolKindName[410:430]:      ToolKindChatStartExecution,
	_ToolKindLowerName[410:430]: ToolKindChatStartExecution,
}

var _ToolKindNames = []string{
	_ToolKindName[0:9],
	_ToolKindName[9:19],
	_ToolKindName[19:29],
	_ToolKindName[29:38],
	_ToolKindName[38:47],
	_ToolKindName[47:58],
	_ToolKindName[58:62],
	_ToolKindName[62:66],
	_ToolKindName[66:78],
	_ToolKindName[78:89],
	_ToolKindName[89:98],
	_ToolKindName[98:114],
	_ToolKindName[114:125],
	_ToolKindName[125:139],
	_ToolKindName[139:151],
	_ToolKindName[151:160],
	_ToolKindName[160:170],
	_ToolKindName[170:174],
	_ToolKindName[174:182],
	_ToolKindName[182:193],
	_ToolKindName[193:207],
	_ToolKindName[207:220],
	_ToolKindName[220:236],
	_ToolKindName[236:250],
	_ToolKindName[250:265],
	_ToolKindName[265:274],
	_ToolKindName[274:288],
	_ToolKindName[288:304],
	_ToolKindName[304:319],
	_ToolKindName[319:328],
	_ToolKindName[328:338],
	_ToolKindName[338:347],
	_ToolKindName[347:359],
	_ToolKindName[359:364],
	_ToolKindName[364:373],
	_ToolKindName[373:383],
	_ToolKindName[383:386],
	_ToolKindName[386:410],
	_ToolKindName[410:430],
}

// ToolKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ToolKindString(s string) (ToolKind, error) {
	if val, ok := _ToolKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ToolKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ToolKind values", s)
}

// ToolKindValues returns all values of the enum
func ToolKindValues() []ToolKind {
	return _ToolKindValues
}

// ToolKindStrings returns a slice of all String values of the enum
func ToolKindStrings() []string {
	strs := make([]string, len(_ToolKindNames))
	copy(strs, _ToolKindNames)
	return strs
}

// IsAToolKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ToolKind) IsAToolKind() bool {
	for _, v := range _ToolKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ToolKind
func (i ToolKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ToolKind
func (i *ToolKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ToolKind should be a string, got %s", data)
	}

	var err error
	*i, err = ToolKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ToolKind
func (i ToolKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ToolKind
func (i *ToolKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = ToolKindString(string(text))
	return err
}
