package domain

import (
	"strings"
	"time"

	"github.com/lkarlslund/koder/internal/accesssettings"
)

//go:generate go tool enumer -type=MessageRole -trimprefix=MessageRole -json -text -values
type MessageRole uint8

const (
	MessageRoleSystem MessageRole = iota
	MessageRoleUser
	MessageRoleAssistant
	MessageRoleTool
)

//go:generate go tool enumer -type=PartKind -trimprefix=PartKind -json -text -values
type PartKind uint8

const (
	PartKindText PartKind = iota
	PartKindAttachment
	PartKindReference
	PartKindReasoning
	PartKindToolCall
	PartKindToolOutput
	PartKindCompaction
	PartKindApprovalRequest
	PartKindQuestion
	PartKindTaskUpdate
	PartKindPlanUpdate
	PartKindUsage
	PartKindSystemNotice
	PartKindEventNotice
)

//go:generate go tool enumer -type=ToolKind -trimprefix=ToolKind -json -text -values
type ToolKind uint8

const (
	ToolKindRead ToolKind = iota + 1
	ToolKindViewImage
	ToolKindShowImage
	ToolKindGlob
	ToolKindGrep
	ToolKindCodeSearch
	ToolKindLint
	ToolKindBash
	ToolKindExecCommand
	ToolKindExecStatus
	ToolKindExecList
	ToolKindExecWriteStdin
	ToolKindExecResize
	ToolKindExecTerminate
	ToolKindExecCleanup
	ToolKindEdit
	ToolKindWrite
	ToolKindTask
	ToolKindQuestion
	ToolKindUpdatePlan
	ToolKindMilestoneList
	ToolKindMilestoneAdd
	ToolKindMilestoneUpdate
	ToolKindMilestonePlan
	ToolKindMilestoneWrite
	ToolKindTodoList
	ToolKindTodoAddItems
	ToolKindTodoUpdateItem
	ToolKindTodoFetchNext
	ToolKindChatList
	ToolKindChatStart
	ToolKindChatPoll
	ToolKindChatArchive
	ToolKindSkill
	ToolKindWebFetch
	ToolKindWebSearch
	ToolKindMCP
	// Legacy sentinel values kept for backward compatibility with stored data.
	ToolKindApplyPatch
	ToolKindChatStartDecomposition
	ToolKindChatStartExecution
)

//go:generate go tool enumer -type=PermissionMode -trimprefix=PermissionMode -json -text -values
type PermissionMode uint8

const (
	PermissionModeAllow PermissionMode = iota
	PermissionModeAsk
	PermissionModeDeny
)

type PermissionOverride struct {
	Tool  ToolKind
	Pattern string
	Action  PermissionMode
}

//go:generate go tool enumer -type=ApprovalStatus -trimprefix=ApprovalStatus -json -text -values
type ApprovalStatus uint8

const (
	ApprovalStatusPending ApprovalStatus = iota
	ApprovalStatusApproved
	ApprovalStatusDenied
)

//go:generate go tool enumer -type=TaskStatus -trimprefix=TaskStatus -json -text -values
type TaskStatus uint8

const (
	TaskStatusPending TaskStatus = iota
	TaskStatusInProgress
	TaskStatusCompleted
	TaskStatusCancelled
)

//go:generate go tool enumer -type=MilestoneStatus -trimprefix=MilestoneStatus -json -text -values
type MilestoneStatus uint8

const (
	MilestoneStatusPending MilestoneStatus = iota
	MilestoneStatusDecomposing
	MilestoneStatusReady
	MilestoneStatusExecuting
	MilestoneStatusCompleted
	MilestoneStatusBlocked
	MilestoneStatusCancelled
)

//go:generate go tool enumer -type=TodoStatus -trimprefix=TodoStatus -json -text -values
type TodoStatus uint8

const (
	TodoStatusPending TodoStatus = iota
	TodoStatusInProgress
	TodoStatusCompleted
)

//go:generate go tool enumer -type=EventKind -trimprefix=EventKind -json -text -values
type EventKind uint8

const (
	EventKindMessageDelta EventKind = iota
	EventKindMessageDone
	EventKindReasoning
	EventKindToolCallDelta
	EventKindUsage
	EventKindToolStart
	EventKindToolResult
	EventKindApprovalAsk
	EventKindApprovalReply
	EventKindTaskUpdate
	EventKindSessionTitle
	EventKindChatTitle
	EventKindError
	EventKindStatus
)

type Session struct {
	ID  ID
	ParentID  *ID
	Title  string
	TitleGeneratedAt  time.Time
	TitleRefreshCount int
	PermissionProfile string
	PermissionRules  []PermissionOverride
	ToolStates  map[ToolKind]bool
	AccessSettings  accesssettings.Settings
	ProjectRoot  string
	ProjectChecksum  string
	AgentsResolved  string
	AgentsSummary  string
	AgentsFiles  []AgentsFile
	AgentsGeneratedAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastMessage  string
}

type WorkflowRole string

type Chat struct {
	ID  ID
	SessionID  ID
	ParentChatID  *ID
	Title  string
	WorkflowRole  WorkflowRole
	ProviderID  string
	ModelID  string
	PermissionProfile  string
	ToolStates  map[ToolKind]bool
	ActiveMilestoneRef  string
	AssignedTodoBucketRef  string
	AssignedTodoRef  ID
	LastKnownContextTokens int
	ContextTokensKnown  bool
	Position  int
	Archived  bool
	QueuedInputs  []QueuedInput
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastMessage  string
}

type ContextUsage struct {
	AnchorTokens int
	TailTokens  int
	LiveTokens  int
	TotalTokens  int
	Estimated  bool
}

//go:generate go tool enumer -type=QueuedInputKind -trimprefix=QueuedInputKind -json -text -values
type QueuedInputKind uint8

const (
	QueuedInputKindSteer QueuedInputKind = iota
	QueuedInputKindQueued
	QueuedInputKindContinue
	QueuedInputKindRejectedSteer
)

const (
	UserMessageSourceUser  = "user"
	UserMessageSourceSteer  = "steer"
	UserMessageSourceQueued  = "queued"
	UserMessageSourceRejectedSteer = "rejected_steer"
	UserMessageSourceAutoGenerated = "auto_generated"
	UserMessageSourceAutoResume  = "auto_resume"
	UserMessageSourceSubchat  = "subchat"
)

type QueuedInput struct {
	ID  ID
	Kind  QueuedInputKind
	Text  string
	Source  string
	TimelineID  ID
	Held  bool
	Attachments []QueuedAttachment
	References  []QueuedReference
	CreatedAt  time.Time
}

// UserMessageSourceForQueuedInput returns the transcript source label for a queued input.
func UserMessageSourceForQueuedInput(item QueuedInput) string {
	if source := strings.TrimSpace(item.Source); source != "" {
		return source
	}
	switch item.Kind {
	case QueuedInputKindSteer:
		return UserMessageSourceSteer
	case QueuedInputKindQueued:
		return UserMessageSourceQueued
	case QueuedInputKindRejectedSteer:
		return UserMessageSourceRejectedSteer
	default:
		return UserMessageSourceUser
	}
}

type QueuedAttachment struct {
	ID  string
	Name  string
	MIME  string
	Path  string
	Size  int64
	Source  string
	Original string
}

type QueuedReference struct {
	Kind  string
	Path  string
	Display string
	Start  int
	End  int
}

type AgentsFile struct {
	Path  string
	Kind  string
	Priority  int
	ModTime  time.Time
	Checksum  string
	Size  int64
	DiscoveredBy string
}

type Message struct {
	ID  ID
	SessionID ID
	ChatID  ID
	Role  MessageRole
	Summary  string
	CreatedAt time.Time
}

type Part struct {
	ID  ID
	MessageID ID
	Kind  PartKind
	Payload  PartPayload
	Body  string `json:"-"`
	MetaJSON  string `json:"-"`
	CreatedAt time.Time
}

type Model struct {
	ID  string
	OwnedBy  string
	SupportsImages  bool
	SupportsPDFs  bool
	CapabilitySource  string
	CapabilitiesKnown bool
}

type Usage struct {
	PromptTokens  int
	CompletionTokens int
	CachedTokens  int
	TotalTokens  int
}

func (u Usage) HasAnyTokens() bool {
	return u.PromptTokens > 0 || u.CompletionTokens > 0 || u.CachedTokens > 0 || u.TotalTokens > 0
}

func (u Usage) Normalized() Usage {
	if u.TotalTokens <= 0 && (u.PromptTokens > 0 || u.CompletionTokens > 0) {
		u.TotalTokens = u.PromptTokens + u.CompletionTokens
	}
	return u
}

func (u Usage) Add(other Usage) Usage {
	u = u.Normalized()
	other = other.Normalized()
	u.PromptTokens += other.PromptTokens
	u.CompletionTokens += other.CompletionTokens
	u.CachedTokens += other.CachedTokens
	u.TotalTokens += other.TotalTokens
	return u.Normalized()
}

// ContextTokens returns the prompt/input token count represented by the usage.
func (u Usage) ContextTokens() (int, bool) {
	u = u.Normalized()
	if u.PromptTokens > 0 {
		return u.PromptTokens, true
	}
	if u.TotalTokens > 0 && u.CompletionTokens >= 0 && u.TotalTokens > u.CompletionTokens {
		return u.TotalTokens - u.CompletionTokens, true
	}
	return 0, false
}

type Event struct {
	Kind  EventKind
	Text  string
	Tool  ToolKind
	ToolCallID string
	ApprovalID ID
	Item  TimelineItem
	Meta  map[string]string
	Usage  Usage
	Err  error
	RawJSON  string
}

const (
	// EventMetaRefresh names a refresh target requested by an event.
	EventMetaRefresh = "refresh"

	// EventMetaPromptProgress marks provider prompt preprocessing progress.
	EventMetaPromptProgress = "prompt_progress"

	// EventRefreshQueue asks chat runtimes to reload queued inputs from storage.
	EventRefreshQueue = "queue"
)