// Code generated by "enumer -type=Kind -trimprefix=ToolKind -transform=snake -json -text -values -output=kind_enumer.go"; DO NOT EDIT.

package toolkind

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _KindName = "file_readview_imageshow_imagefile_globfile_grepcode_searchlintbashexec_commandexec_statusexec_listexec_write_stdinexec_resizeexec_terminateexec_cleanupfile_editfile_writetaskquestionupdate_planmilestone_listmilestone_addmilestone_updatemilestone_planmilestone_writetask_listtask_add_itemstask_update_itemtask_fetch_nexttasks_addtasks_updatechat_listchat_startchat_sendchat_cancelchat_archivechat_renameskillweb_fetchweb_searchmcp"

var _KindIndex = [...]uint16{0, 9, 19, 29, 38, 47, 58, 62, 66, 78, 89, 98, 114, 125, 139, 151, 160, 170, 174, 182, 193, 207, 220, 236, 250, 265, 274, 288, 304, 319, 328, 340, 349, 359, 368, 379, 391, 402, 407, 416, 426, 429}

const _KindLowerName = "file_readview_imageshow_imagefile_globfile_grepcode_searchlintbashexec_commandexec_statusexec_listexec_write_stdinexec_resizeexec_terminateexec_cleanupfile_editfile_writetaskquestionupdate_planmilestone_listmilestone_addmilestone_updatemilestone_planmilestone_writetask_listtask_add_itemstask_update_itemtask_fetch_nexttasks_addtasks_updatechat_listchat_startchat_sendchat_cancelchat_archivechat_renameskillweb_fetchweb_searchmcp"

func (i Kind) String() string {
	i -= 1
	if i >= Kind(len(_KindIndex)-1) {
		return fmt.Sprintf("Kind(%d)", i+1)
	}
	return _KindName[_KindIndex[i]:_KindIndex[i+1]]
}

func (Kind) Values() []string {
	return KindStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _KindNoOp() {
	var x [1]struct{}
	_ = x[ToolKindFileRead-(1)]
	_ = x[ToolKindViewImage-(2)]
	_ = x[ToolKindShowImage-(3)]
	_ = x[ToolKindFileGlob-(4)]
	_ = x[ToolKindFileGrep-(5)]
	_ = x[ToolKindCodeSearch-(6)]
	_ = x[ToolKindLint-(7)]
	_ = x[ToolKindBash-(8)]
	_ = x[ToolKindExecCommand-(9)]
	_ = x[ToolKindExecStatus-(10)]
	_ = x[ToolKindExecList-(11)]
	_ = x[ToolKindExecWriteStdin-(12)]
	_ = x[ToolKindExecResize-(13)]
	_ = x[ToolKindExecTerminate-(14)]
	_ = x[ToolKindExecCleanup-(15)]
	_ = x[ToolKindFileEdit-(16)]
	_ = x[ToolKindFileWrite-(17)]
	_ = x[ToolKindTask-(18)]
	_ = x[ToolKindQuestion-(19)]
	_ = x[ToolKindUpdatePlan-(20)]
	_ = x[ToolKindMilestoneList-(21)]
	_ = x[ToolKindMilestoneAdd-(22)]
	_ = x[ToolKindMilestoneUpdate-(23)]
	_ = x[ToolKindMilestonePlan-(24)]
	_ = x[ToolKindMilestoneWrite-(25)]
	_ = x[ToolKindTaskList-(26)]
	_ = x[ToolKindTaskAddItems-(27)]
	_ = x[ToolKindTaskUpdateItem-(28)]
	_ = x[ToolKindTaskFetchNext-(29)]
	_ = x[ToolKindTasksAdd-(30)]
	_ = x[ToolKindTasksUpdate-(31)]
	_ = x[ToolKindChatList-(32)]
	_ = x[ToolKindChatStart-(33)]
	_ = x[ToolKindChatSend-(34)]
	_ = x[ToolKindChatCancel-(35)]
	_ = x[ToolKindChatArchive-(36)]
	_ = x[ToolKindChatRename-(37)]
	_ = x[ToolKindSkill-(38)]
	_ = x[ToolKindWebFetch-(39)]
	_ = x[ToolKindWebSearch-(40)]
	_ = x[ToolKindMCP-(41)]
}

var _KindValues = []Kind{ToolKindFileRead, ToolKindViewImage, ToolKindShowImage, ToolKindFileGlob, ToolKindFileGrep, ToolKindCodeSearch, ToolKindLint, ToolKindBash, ToolKindExecCommand, ToolKindExecStatus, ToolKindExecList, ToolKindExecWriteStdin, ToolKindExecResize, ToolKindExecTerminate, ToolKindExecCleanup, ToolKindFileEdit, ToolKindFileWrite, ToolKindTask, ToolKindQuestion, ToolKindUpdatePlan, ToolKindMilestoneList, ToolKindMilestoneAdd, ToolKindMilestoneUpdate, ToolKindMilestonePlan, ToolKindMilestoneWrite, ToolKindTaskList, ToolKindTaskAddItems, ToolKindTaskUpdateItem, ToolKindTaskFetchNext, ToolKindTasksAdd, ToolKindTasksUpdate, ToolKindChatList, ToolKindChatStart, ToolKindChatSend, ToolKindChatCancel, ToolKindChatArchive, ToolKindChatRename, ToolKindSkill, ToolKindWebFetch, ToolKindWebSearch, ToolKindMCP}

var _KindNameToValueMap = map[string]Kind{
	_KindName[0:9]:          ToolKindFileRead,
	_KindLowerName[0:9]:     ToolKindFileRead,
	_KindName[9:19]:         ToolKindViewImage,
	_KindLowerName[9:19]:    ToolKindViewImage,
	_KindName[19:29]:        ToolKindShowImage,
	_KindLowerName[19:29]:   ToolKindShowImage,
	_KindName[29:38]:        ToolKindFileGlob,
	_KindLowerName[29:38]:   ToolKindFileGlob,
	_KindName[38:47]:        ToolKindFileGrep,
	_KindLowerName[38:47]:   ToolKindFileGrep,
	_KindName[47:58]:        ToolKindCodeSearch,
	_KindLowerName[47:58]:   ToolKindCodeSearch,
	_KindName[58:62]:        ToolKindLint,
	_KindLowerName[58:62]:   ToolKindLint,
	_KindName[62:66]:        ToolKindBash,
	_KindLowerName[62:66]:   ToolKindBash,
	_KindName[66:78]:        ToolKindExecCommand,
	_KindLowerName[66:78]:   ToolKindExecCommand,
	_KindName[78:89]:        ToolKindExecStatus,
	_KindLowerName[78:89]:   ToolKindExecStatus,
	_KindName[89:98]:        ToolKindExecList,
	_KindLowerName[89:98]:   ToolKindExecList,
	_KindName[98:114]:       ToolKindExecWriteStdin,
	_KindLowerName[98:114]:  ToolKindExecWriteStdin,
	_KindName[114:125]:      ToolKindExecResize,
	_KindLowerName[114:125]: ToolKindExecResize,
	_KindName[125:139]:      ToolKindExecTerminate,
	_KindLowerName[125:139]: ToolKindExecTerminate,
	_KindName[139:151]:      ToolKindExecCleanup,
	_KindLowerName[139:151]: ToolKindExecCleanup,
	_KindName[151:160]:      ToolKindFileEdit,
	_KindLowerName[151:160]: ToolKindFileEdit,
	_KindName[160:170]:      ToolKindFileWrite,
	_KindLowerName[160:170]: ToolKindFileWrite,
	_KindName[170:174]:      ToolKindTask,
	_KindLowerName[170:174]: ToolKindTask,
	_KindName[174:182]:      ToolKindQuestion,
	_KindLowerName[174:182]: ToolKindQuestion,
	_KindName[182:193]:      ToolKindUpdatePlan,
	_KindLowerName[182:193]: ToolKindUpdatePlan,
	_KindName[193:207]:      ToolKindMilestoneList,
	_KindLowerName[193:207]: ToolKindMilestoneList,
	_KindName[207:220]:      ToolKindMilestoneAdd,
	_KindLowerName[207:220]: ToolKindMilestoneAdd,
	_KindName[220:236]:      ToolKindMilestoneUpdate,
	_KindLowerName[220:236]: ToolKindMilestoneUpdate,
	_KindName[236:250]:      ToolKindMilestonePlan,
	_KindLowerName[236:250]: ToolKindMilestonePlan,
	_KindName[250:265]:      ToolKindMilestoneWrite,
	_KindLowerName[250:265]: ToolKindMilestoneWrite,
	_KindName[265:274]:      ToolKindTaskList,
	_KindLowerName[265:274]: ToolKindTaskList,
	_KindName[274:288]:      ToolKindTaskAddItems,
	_KindLowerName[274:288]: ToolKindTaskAddItems,
	_KindName[288:304]:      ToolKindTaskUpdateItem,
	_KindLowerName[288:304]: ToolKindTaskUpdateItem,
	_KindName[304:319]:      ToolKindTaskFetchNext,
	_KindLowerName[304:319]: ToolKindTaskFetchNext,
	_KindName[319:328]:      ToolKindTasksAdd,
	_KindLowerName[319:328]: ToolKindTasksAdd,
	_KindName[328:340]:      ToolKindTasksUpdate,
	_KindLowerName[328:340]: ToolKindTasksUpdate,
	_KindName[340:349]:      ToolKindChatList,
	_KindLowerName[340:349]: ToolKindChatList,
	_KindName[349:359]:      ToolKindChatStart,
	_KindLowerName[349:359]: ToolKindChatStart,
	_KindName[359:368]:      ToolKindChatSend,
	_KindLowerName[359:368]: ToolKindChatSend,
	_KindName[368:379]:      ToolKindChatCancel,
	_KindLowerName[368:379]: ToolKindChatCancel,
	_KindName[379:391]:      ToolKindChatArchive,
	_KindLowerName[379:391]: ToolKindChatArchive,
	_KindName[391:402]:      ToolKindChatRename,
	_KindLowerName[391:402]: ToolKindChatRename,
	_KindName[402:407]:      ToolKindSkill,
	_KindLowerName[402:407]: ToolKindSkill,
	_KindName[407:416]:      ToolKindWebFetch,
	_KindLowerName[407:416]: ToolKindWebFetch,
	_KindName[416:426]:      ToolKindWebSearch,
	_KindLowerName[416:426]: ToolKindWebSearch,
	_KindName[426:429]:      ToolKindMCP,
	_KindLowerName[426:429]: ToolKindMCP,
}

var _KindNames = []string{
	_KindName[0:9],
	_KindName[9:19],
	_KindName[19:29],
	_KindName[29:38],
	_KindName[38:47],
	_KindName[47:58],
	_KindName[58:62],
	_KindName[62:66],
	_KindName[66:78],
	_KindName[78:89],
	_KindName[89:98],
	_KindName[98:114],
	_KindName[114:125],
	_KindName[125:139],
	_KindName[139:151],
	_KindName[151:160],
	_KindName[160:170],
	_KindName[170:174],
	_KindName[174:182],
	_KindName[182:193],
	_KindName[193:207],
	_KindName[207:220],
	_KindName[220:236],
	_KindName[236:250],
	_KindName[250:265],
	_KindName[265:274],
	_KindName[274:288],
	_KindName[288:304],
	_KindName[304:319],
	_KindName[319:328],
	_KindName[328:340],
	_KindName[340:349],
	_KindName[349:359],
	_KindName[359:368],
	_KindName[368:379],
	_KindName[379:391],
	_KindName[391:402],
	_KindName[402:407],
	_KindName[407:416],
	_KindName[416:426],
	_KindName[426:429],
}

// KindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func KindString(s string) (Kind, error) {
	if val, ok := _KindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _KindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Kind values", s)
}

// KindValues returns all values of the enum
func KindValues() []Kind {
	return _KindValues
}

// KindStrings returns a slice of all String values of the enum
func KindStrings() []string {
	strs := make([]string, len(_KindNames))
	copy(strs, _KindNames)
	return strs
}

// IsAKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Kind) IsAKind() bool {
	for _, v := range _KindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Kind
func (i Kind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Kind
func (i *Kind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Kind should be a string, got %s", data)
	}

	var err error
	*i, err = KindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Kind
func (i Kind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Kind
func (i *Kind) UnmarshalText(text []byte) error {
	var err error
	*i, err = KindString(string(text))
	return err
}
