// Code generated by "enumer -type=Turn -trimprefix=Turn -transform=snake -json -text -values -output=turn_enumer.go"; DO NOT EDIT.

package chat

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TurnName = "idlequeuedpreparingcompactingwaiting_llmstreamingrunning_toolswaiting_approvalcancellingerrored"

var _TurnIndex = [...]uint8{0, 4, 10, 19, 29, 40, 49, 62, 78, 88, 95}

const _TurnLowerName = "idlequeuedpreparingcompactingwaiting_llmstreamingrunning_toolswaiting_approvalcancellingerrored"

func (i Turn) String() string {
	if i >= Turn(len(_TurnIndex)-1) {
		return fmt.Sprintf("Turn(%d)", i)
	}
	return _TurnName[_TurnIndex[i]:_TurnIndex[i+1]]
}

func (Turn) Values() []string {
	return TurnStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TurnNoOp() {
	var x [1]struct{}
	_ = x[TurnIdle-(0)]
	_ = x[TurnQueued-(1)]
	_ = x[TurnPreparing-(2)]
	_ = x[TurnCompacting-(3)]
	_ = x[TurnWaitingLLM-(4)]
	_ = x[TurnStreaming-(5)]
	_ = x[TurnRunningTools-(6)]
	_ = x[TurnWaitingApproval-(7)]
	_ = x[TurnCancelling-(8)]
	_ = x[TurnErrored-(9)]
}

var _TurnValues = []Turn{TurnIdle, TurnQueued, TurnPreparing, TurnCompacting, TurnWaitingLLM, TurnStreaming, TurnRunningTools, TurnWaitingApproval, TurnCancelling, TurnErrored}

var _TurnNameToValueMap = map[string]Turn{
	_TurnName[0:4]:        TurnIdle,
	_TurnLowerName[0:4]:   TurnIdle,
	_TurnName[4:10]:       TurnQueued,
	_TurnLowerName[4:10]:  TurnQueued,
	_TurnName[10:19]:      TurnPreparing,
	_TurnLowerName[10:19]: TurnPreparing,
	_TurnName[19:29]:      TurnCompacting,
	_TurnLowerName[19:29]: TurnCompacting,
	_TurnName[29:40]:      TurnWaitingLLM,
	_TurnLowerName[29:40]: TurnWaitingLLM,
	_TurnName[40:49]:      TurnStreaming,
	_TurnLowerName[40:49]: TurnStreaming,
	_TurnName[49:62]:      TurnRunningTools,
	_TurnLowerName[49:62]: TurnRunningTools,
	_TurnName[62:78]:      TurnWaitingApproval,
	_TurnLowerName[62:78]: TurnWaitingApproval,
	_TurnName[78:88]:      TurnCancelling,
	_TurnLowerName[78:88]: TurnCancelling,
	_TurnName[88:95]:      TurnErrored,
	_TurnLowerName[88:95]: TurnErrored,
}

var _TurnNames = []string{
	_TurnName[0:4],
	_TurnName[4:10],
	_TurnName[10:19],
	_TurnName[19:29],
	_TurnName[29:40],
	_TurnName[40:49],
	_TurnName[49:62],
	_TurnName[62:78],
	_TurnName[78:88],
	_TurnName[88:95],
}

// TurnString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TurnString(s string) (Turn, error) {
	if val, ok := _TurnNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TurnNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Turn values", s)
}

// TurnValues returns all values of the enum
func TurnValues() []Turn {
	return _TurnValues
}

// TurnStrings returns a slice of all String values of the enum
func TurnStrings() []string {
	strs := make([]string, len(_TurnNames))
	copy(strs, _TurnNames)
	return strs
}

// IsATurn returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Turn) IsATurn() bool {
	for _, v := range _TurnValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Turn
func (i Turn) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Turn
func (i *Turn) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Turn should be a string, got %s", data)
	}

	var err error
	*i, err = TurnString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Turn
func (i Turn) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Turn
func (i *Turn) UnmarshalText(text []byte) error {
	var err error
	*i, err = TurnString(string(text))
	return err
}
